### ISSUE TITLE
Consumer API :: Improve search performance

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#1000]
Replace string search with the index search

**Comment by abhishekshenoy** [comment]
@wajda Currently as we store all the execution plan data t, would it help to have calendar search option from the UI which by default only looks back 10 days

**Comment by wajda** [comment]
Not sure I understand what you mean, but the date range filter is implemented and is optional and covers the full range of available metadata by default. If it's not, it would be a bug.
