### ISSUE TITLE
Cannot send lineage data .... Read timed out error 

### ISSUE THREAD

**Issue by vchichil97** [AbsaOSS/spline#1003]
I am trying to integrate my spark jobs with spline. Added the below dependency 
<dependency>
    <groupId>za.co.absa.spline.agent.spark</groupId>
    <artifactId>agent-core_2.12</artifactId>
    <version>0.6.1</version>
</dependency>

**Error :** 
WARN za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher: Proceeding after an error occurred in an underlying dispatcher: za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher
java.lang.RuntimeException: Cannot send lineage data to the URL

Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Observations :** 
The lineage data seems to be getting generated as the json message is visible in the yarn logs after adding this property (spline.lineageDispatcher=composite
spline.lineageDispatcher.composite.dispatchers=logging,http) but is not getting posted to the spline url.

What is the resolution for this error ?

**Comment by cerveada** [comment]
What is happening on the server side? Are there any errors?
