### ISSUE TITLE
How to disable ssl validation when Rest server connects to ArangoDB

### ISSUE THREAD

**Issue by mikemowgli** [AbsaOSS/spline#1004]
## Background [Optional]
I used the ArangoDB operator to deploy on Kubernetes. By default, it exposes the DB on an SSL protected endpoint, using a self-signed certificate. I'm able to create the spline DB with spline-admin using the "--disable-ssl-validation" flag, but it isn't documented how the Rest server could disable ssl validation. At the moment, the rest server fails to connect to the DB with this error:
```
16:27:07.393 [main] INFO  z.c.a.s.p.ArangoRepoConfig$$EnhancerBySpringCGLIB$$cf86eada - Spline database URL: arangodbs://root:*****@spline-db:8529/spline
16:27:08.399 [pool-1-thread-1] WARN  c.a.i.velocystream.VstCommunication - Could not connect to host[addr=spline-db,port=8529]
```

## Question
Could you document the all environment variables accepted by the rest server, besides the ones already present here: https://absaoss.github.io/spline/#configuration

**Comment by mikemowgli** [comment]
Also note that I've tried `vst+ssl` instead of `arangodbs`, but then the error became: ` Caused by: java.net.MalformedURLException: vst+ssl://root:<REDACTED>@spline-db:8529/spline (of class java.lang.String)`

**Comment by mikemowgli** [comment]
I figured how to do it by using the (AFAIK) undocumented environment variable `spline.database.disableSslValidation=true` by looking here in the code: https://github.com/AbsaOSS/spline/blob/develop/persistence/src/main/scala/za/co/absa/spline/persistence/ArangoRepoConfig.scala#L66

**Comment by mikemowgli** [comment]
I'm leaving this open in case the maintainer wants to update the doc.

**Comment by wajda** [comment]
The URL format is the same as in the admin - use `arangodb://` for plain or `arangodbs://` for secured connection. It's _not_ the name of the ArangoDB protocol. Under the hood it uses both VST and HTTP depending on the type of request (AQL/Foxx). For secured connections it's VST+SSL and HTTPS respectively.

> Could you document the all environment variables accepted by the rest server

Updated - https://absaoss.github.io/spline/#configuration
`SPLINE_DATABASE_DISABLE_SSL_VALIDATION` property was missing there. Sorry.
