### ISSUE TITLE
enabling data lineage from spark session created in java

### ISSUE THREAD

**Issue by neilmackenzie** [AbsaOSS/spline#106]
In my own project I generate a lot of java code for running spark processes.
I create the sparksession as  follows in Java: 

SparkSession spark = SparkSession
				  .builder()
				  .appName("Java Spark SQL basic example")
				  .config("hadoop.home.dir", "C:/Users/neil/hadoop")
				  .master("local[*]")
				  .getOrCreate();

Is it possible to set lineage Enabled on this spark session or does it need to be done on a spark session created using Scala?
The documented approach of:
 import za.co.absa.spline.core.SparkLineageInitializer._
 sparkSession.enableLineageTracking()
Is specific to Scala.
Thanks.

**Comment by wajda** [comment]
Sure, you can enable it from Java as well. Scala is still Java, so you can access any Scala constructs from Java albeit the code could look somewhat awkward.

        SparkSession spark = sparkBuilder.getOrCreate();

        SparkLineageInitializer.SparkSessionWrapper sessionWrapper = new SparkLineageInitializer.SparkSessionWrapper(spark);
        sessionWrapper.enableLineageTracking(sessionWrapper.enableLineageTracking$default$1());
