### ISSUE TITLE
Upgrade to ArangoDB 3.10

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#1115]
**ArangoDB 3.10** comes with a number of improvements that we could benefit from, like (but not limited to) the following:
1. Native ARM Support
2. Computed Values
3. Inverted collection indexes and other search mechanism improvements
4. Improved `autoincrement` key generator
5. Faster sync replication

https://www.arangodb.com/docs/stable/release-notes-new-features310.html

**Comment by cerveada** [comment]
Should we put this in 1.0.0 since 3.9 doesn't work on M1 and 3.8 is not supported by Spline anymore?

https://www.arangodb.com/docs/stable/release-notes-new-features310.html#native-arm-support

**Comment by wajda** [comment]
Ok, let's do it. Let's just test if it's fully compatible with our codebase.
