### ISSUE TITLE
Getting  error on UI:Server returned code: 0. Http failure response for http://URL:9091/consumer/execution-events

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline#1130]
## Describe the bug
after installatiom when opening the URL :
http://MYURL:9090/app/dashboard
i get  error:
Server returned code: 0. Http failure response for consumer/execution-events

## Versions

Please provide versions of: Spline, Spark and Scala that were in use when the bug happened.
Spline -0.5.6
Spark-3.3.0
Scala-2.1.2
in Databricks under Azure

**Comment by cerveada** [comment]
Answered here - https://github.com/AbsaOSS/spline/issues/743#issuecomment-651109409

**Comment by cerveada** [comment]
It means the UI can't reach the server either the consumer URL you configured in the UI is wrong or the server is not reachable via the network.
