### ISSUE TITLE
Codeless Spline initialization

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#131]
... via `spark.sql.queryExecutionListeners` Spark config property

**Comment by wajda** [comment]
This might also solve the following issues:
- #48 
- #43 
- #106

**Comment by wajda** [comment]
I think we need to support three way of Spline inialization:
1. Scala mixin - `sparkSession.enableLineageTracking()`
1. Utility method - `SparkLineageInitializer.enableLineageTracking(sparkSession)`
1. Codeless via Spark config

So the users would be able to use whatever they like depending on their technology stack and deployment requirements.

**Comment by lokm01** [comment]
Great idea!

**Comment by wajda** [comment]
https://github.com/apache/spark/commit/7703b46d2843db99e28110c4c7ccf60934412504
