### ISSUE TITLE
HDFS factory not working.

### ISSUE THREAD

**Issue by larryxia-ddl** [AbsaOSS/spline#14]
I found za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory not working, because this line will throw exception. 

override def createDataLineageReader(): DataLineageReader = throw new UnsupportedOperationException

even I bypass this issue by comment out call in DatalineageListener, I found the hdfs output is not correct, there is always only one json record export to the log file, it seem it was overwrite every time. 

It seems this feature is not ready yet.  please advise.

**Comment by wajda** [comment]
Yes, persistence to HDFS is experimental and isn't tested well. A lineage file is rewritten as intended. The original idea for HDFS persistence was to store a lineage file next to the parquet file containing the data. So that you always have data and its lineage in one place, easy to access. When the data file is rewritten, the lineage file is also rewritten respectively. We didn't consider appending data use case.
HDFS persistor didn't received enough attention recently. If you have ides how to improve it, we will appreciate a PR.

**Comment by Roshni1988** [comment]
Hi larryxia-ddl ,

Were you able to start the UI, when you are trying to use the data saved from HDFS?

I have my data  stored in HDFS, but i am not able to start the spline UI  using the below command

java -jar spline-web-0.2.5-exec-war.jar -Dspline.hdfs.file.name=hdfs://quickstart.cloudera:8020/user/root/spline -Dspline.hdfs.file.permissions=777

Am I Doing something wrong here.. Kindly Help as this is Little urgent for me.

Below is the logs i get and it's get stuck

[root@quickstart spline_jars]# java -jar spline-web-0.2.5-exec-war.jar -Dspline.hdfs.file.name=hdfs://quickstart.cloudera:8020/user/root/spline -Dspline.hdfs.file.permissions=777 -httpPort 1234
Jan 17, 2018 5:59:03 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-1234"]
Jan 17, 2018 5:59:03 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Jan 17, 2018 5:59:03 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
Jan 17, 2018 5:59:12 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jan 17, 2018 5:59:12 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-1234"]

and while opening the localhost:1234 in the browser i get page not found issue.

**Comment by sergiobanos** [comment]
Hi, 

I have being looking Spline and seems really nice. When I try to persist on HDFS, I am facing the following problem as larryxia-ddl  ( details below )

Spline.properties

spline.persistence.factory=za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory
spline.hdfs.file.name= hdfs://10.0.2.15:8020/user/cloudera/OutputLineage.txt
spline.hdfs.file.permissions=777

Question1: Is there something incorrect in the above settings that prevent me to see the hdfs output?
Question 2: Is there a planned release where this issue can be addressed?. Is there a workaround I can make to make it work?

Help is appreciated - 

Thanks very much for your contribution!

Details:

Exception in thread "main" java.lang.UnsupportedOperationException
	at za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory.createDataLineageReader(HdfsPersistenceFactory.scala:61)
	at za.co.absa.spline.core.DataLineageListener.<init>(DataLineageListener.scala:43)
	at za.co.absa.spline.core.SparkLineageInitializer$SparkSessionWrapper.attemptInitialization(SparkLineageInitializer.scala:72)
	at za.co.absa.spline.core.SparkLineageInitializer$SparkSessionWrapper.liftedTree1$1(SparkLineageInitializer.scala:58)
	at za.co.absa.spline.core.SparkLineageInitializer$SparkSessionWrapper.enableLineageTracking(SparkLineageInitializer.scala:57)

**Comment by wajda** [comment]
Hm, I was under impression that this bug has been fixed a long time ago. Sorry about that/ I will take a look and push a fix asap. Most likely the fixed has been made in our internal branch and has yet to be published on github.

**Comment by wajda** [comment]
Please try 0.2.6 release, should be working now.

**Comment by sergiobanos** [comment]
Working perfectly. Thanks Wajda!
