### ISSUE TITLE
spline-spark-adapter-api has spark dependencies in compile scope

### ISSUE THREAD

**Issue by igreenfield** [AbsaOSS/spline#175]
in the pom there are dependencies to spark so it create mixed spark version...

**Comment by wajda** [comment]
What do you mean by mixed spark version? Where is it created?

**Comment by wajda** [comment]
Ok, I think I got the point.
Spark should be defined as "provided", for sure.

**Comment by igreenfield** [comment]
When this is going to be in release version?
