### ISSUE TITLE
Blank detailed lineage graph

### ISSUE THREAD

**Issue by algattik** [AbsaOSS/spline#181]
After double-clicking on "Databricks Shell" in the image below, about 70% of the time the resulting screen in blank.
<img width="217" alt="image" src="https://user-images.githubusercontent.com/22099722/55733476-2eab2e80-5a1e-11e9-9be3-054e8c83d5f8.png">

Sometimes clicking the "eye" filters at the top of the screen causes the lineage to be displayed correctly.

Chrome console shows:
core.js:1673 ERROR TypeError: Cannot read property 'unselectAll' of undefined
    at e.refreshSelectedNode (graph.component.ts:153)
    at e.ngOnChanges (graph.component.ts:74)
core.js:1673 ERROR TypeError: Cannot read property '_typeHint' of undefined
    at o (types.ts:65)
    at Object.t.typeOfExpr (types.ts:57)
    at e.getText (expression-render.service.ts:65)
    at c (graph-builder.ts:64)
    at graph-builder.ts:40

Tried with web jar 0.3.6 & 0.3.7-SNAPSHOT build.

**Comment by wajda** [comment]
Confirmed.

**Comment by manthanthakker** [comment]
Is this fixed? Am not able to see any detailed graph. Also, which version of spline does not have this issue?

**Comment by wajda** [comment]
It is fixed in 0.3.7, but it's not released yet. We're still finishing the last bits. It should be out in the next few days.
