### ISSUE TITLE
Jar File Context startup failed due to previous errors

### ISSUE THREAD

**Issue by manthanthakker** [AbsaOSS/spline#183]
Hi,

While running this 
`java -jar spline-web-0.3.6-exec-war.jar -Dspline.mongodb.url=mongodb://localhost:27017 -Dspline.mongodb.name=test` -httpPort 8082

I get the following log
 `Apr 07, 2019 11:56:23 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8082"]
Apr 07, 2019 11:56:23 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Apr 07, 2019 11:56:23 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
Apr 07, 2019 11:56:26 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [*] took [129] milliseconds.
Apr 07, 2019 11:56:26 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Apr 07, 2019 11:56:26 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8082"]`

I am running this locally on my windows machine. Works perfectly on my MacBook.

**Comment by wajda** [comment]
We just tested it on Windows 10 and and it worked perfectly fine.
Can you give us more details? What Windows version do you have? What JRE version do you use?

Also please check if the logs are complete. It says that startup failed due to previous errors, but there is no errors appear above in the posted logs.

**Comment by manthanthakker** [comment]
Looks like in log4j properties in the rootlogger is set to INFO, is there any way I could override it to debug while running the jar to see more detailed logs in conf/logs folder?

**Comment by wajda** [comment]
To be honest I don't know how to do it in executable jar (we use [this plugin](http://tomcat.apache.org/maven-plugin-trunk/executable-war-jar.html) for it). But you can try it with normal WAR file. It has no embedded logging conf, so the you can configure logging on your Web-container's level.

**Comment by manthanthakker** [comment]
Deployed war file on a local tomcat instance and made it worked fine. Would be great if we could set the logging level to Debug in future to troubleshoot some startup errors.

**Comment by wajda** [comment]
Thanks. We'll most likely move toward Docker in the future versions. I think it will be easier to configure the logging there.
