### ISSUE TITLE
scala 2.12 support

### ISSUE THREAD

**Issue by igreenfield** [AbsaOSS/spline#212]
from spark 2.4.1 the release move to scala 2.12 do you have release for scala 2.12?

**Comment by wajda** [comment]
Hi @igreenfield,
We didn't test Spline with Scala 2.12 yet, but there is a chance that it will work.
Did you try it?

**Comment by igreenfield** [comment]
You need to compile it for scala 2.12

**Comment by wajda** [comment]
Ok, will put it in a backlog. Thanks.

**Comment by wajda** [comment]
According to the [documentation](https://spark.apache.org/docs/latest/) 
> Support for Scala 2.11 is deprecated as of Spark 2.4.1 and will be removed in **Spark 3.0**
So I'll put this ticket into Spline 0.4 backlog

**Comment by wajda** [comment]
Per agreement with Enceladus team we will also support **Scala 2.11** for as long as we support **Spark 2.4**. So we need to cross-compile for both Scala versions.

**Comment by igreenfield** [comment]
can you add cross compile for both? I really need it...

**Comment by wajda** [comment]
Hi @igreenfield, sure that would be awesome, thank you for that! Let's discuss the details next week if you don't mind. We have an ongoing refactoring in 0.4 that will affect POMs and entire project structure (moving, renaming, splitting modules etc). It needs to be finished before we could further change POMs. I will contact you when it's done.

Regarding Spark 2.2 we will deprecate it in Spline 0.4 (#230). Or we may even stop supporting 2.2 at all, depending on how badly it will hold us from moving forward with other stuff.

**Comment by wajda** [comment]
@igreenfield, are you still interested in implementing a cross compilation with Scala 2.12? Do you know how to do it with Maven, or should we leverage SBT for it?

**Comment by igreenfield** [comment]
@wajda 
1. Yes, I still want to do it. 
2. Yes, I know how to do it. it can be done with maven. there are 2 ways to do it:
  a. like spark changing pom.xml with script.
  b. sub-modules with symlinks.

What you think?

**Comment by wajda** [comment]
Will it be compatible with Release plugin and Sonatype plugin?

**Comment by igreenfield** [comment]
I think no.

**Comment by wajda** [comment]
:)
So, the point is that we have automated test, release and deploy builds here - https://teamcity.jetbrains.com/project/OpenSourceProjects_AbsaOSSSpline
and obviously we don't want to break it.
Basically whatever we do with POMs, as long as it is can be built/released/deployed using TeamCity and it's default public agents pool, we are fine with that.
Also, there should be an easy way to roll out the project on a new developer machine and start working with no hassle. Currently we rely on Maven support by modern IDEs (especially by IDEA). So  if introduce some custom and advanced changes to the POM structure that prevents IDEs from being able to understand it, then we should also create a script of something to easily set up a project configuration on a fresh developer machine.

**Comment by igreenfield** [comment]
so I will go with spark...

**Comment by wajda** [comment]
Please note that "Develop" branch is still deep under development, contains non-implemented pieces as is not actually working end-to-end. It will get more complete and usable in the following couple of weeks. Just FYI.

**Comment by igreenfield** [comment]
would you be able to ping me when is done so I will start?

**Comment by igreenfield** [comment]
My plan is:
1. Add scalaMajorVersion to artifactId to all jars (_2.11)
2. Add profiles: scala_2.12, scala_2.11
3. Add scripts to replace scala version

**Comment by wajda** [comment]
You can start, the major part of refactoring is done and the project structure is more or less stable. The only thing that you won't be able to do is to test Spline in action. But you don't necessarily need it, right? So I think you can start working on it.

**Comment by igreenfield** [comment]
as I see now `spline-persistence-mongo` is not in develop branch... and it should be...

**Comment by wajda** [comment]
Migration tool depends on the old Spline 0.3 `spline-persistence-mongo`. The idea is to pull old data with the old DAO. There is no Mongo in Spline 0.4.
I would explain you the new Spline vision and architecture, but I don't see your email address. Can you ping me on email?

**Comment by igreenfield** [comment]
if we build `migration tool` for scala 2.12 the dependencies also should be scala 2.12 so we must compile all for scala 2.12

**Comment by wajda** [comment]
What about making an exception for `migration-tool` module, having it only compiled with 2.11? The migration tool will be changed so that it only depends on "old" Spline, and will have little to no dependency on the new modules. See #251

**Comment by wajda** [comment]
In the worst case we can even extract the migrator tool into a separate project

**Comment by igreenfield** [comment]
we can compile it only for 2.11.

but I think it is better to move it to its own repo

**Comment by igreenfield** [comment]
I think your parent pom needs to be fixed. when can we talk?

**Comment by LyndonArmitage** [comment]
Hi Alex,
We have just started using Spline where I work and consider it a great benefit so far thanks!

Recently I was looking into updating our used Spark versions and Scala versions (from 2.11 to 2.12) and ran into issues that ultimately stemmed from Spline being compiled at version 2.11 only.
For the sake of those searching the error was a standard class not found exception:
`java.lang.NoClassDefFoundError: scala/Product$class`

That's not too big a deal for us at the moment since the benefits of Spline outweigh any immediate benefits of an update to Scala but eventually we will want to update.

So I was wondering on what the timescale for a version that supports 2.12? I am aware you have limited resources and are working to refactor internals for 0.4 so please don't feel pressured into promising anything exact.

Thanks again for the fantastic tool!

**Comment by wajda** [comment]
Thanks @LyndonArmitage
No, I won't give you any exact promise :) But I can assure you that, yes, we will upgrade. We decreased the priority for this issue after Spark decided to return to Scala 2.11 being their default. And also implementing cross-compilation will be much easier when we extract Spline Spark Agent into a separate project, which will happen as soon as we stabilize the lineage harvesting protocol more or less. So I'd say we are talking about a couple of months timeframe. 0.4 is almost there. The next versions will be released on more stable schedule.

**Comment by LyndonArmitage** [comment]
Thanks Alex! Glad to hear! Sounds like you have a handle on everything and good plan going forward. 
The couple of months timeframe is fine for my use case! I just wanted to clarify what had changed since you last commented on this ticket.
I look forward to seeing 0.4!
