### ISSUE TITLE
Blank Detailed Lineage Graph 

### ISSUE THREAD

**Issue by manthanthakker** [AbsaOSS/spline#218]
Clicking on the detailed graph button displays a blank page.

Debugger: ,
core.js:15724 ERROR TypeError: Cannot read property '_typeHint' of undefined
    at r (types.ts:65)
    at Object.t.typeOfExpr (types.ts:57)
    at e.getText (expression-render.service.ts:65)
    at c (graph-builder.ts:69)
    at graph-builder.ts:43
    at Array.map (<anonymous>)
    at Object.t.lineageToGraph (graph-builder.ts:42)
    at graph.component.ts:100
    at t.invoke (zone.js:391)
    at e.run (zone.js:150)
rI @ core.js:15724
I see the joining condition variable to be undefined in the GraphBuilder.ts file getLabel function for inner join case. 
While typecasting IOperation to IJoin it's not able to find the 'condition' parameter.

**Comment by wajda** [comment]
@manthanthakker, what Spline version you are using? It resembles #181 bug that was fixed in 0.3.7.
Can you double check you are actually using 0.3.7?

**Comment by manthanthakker** [comment]
Yes, I am using the 0.3.7 release.

**Comment by wajda** [comment]
Can you provide more details to reproduce the issue?

**Comment by wajda** [comment]
Got it. It happens when a join condition is `None`, e.g. in case of a cross join. Will fix it.

**Comment by manthanthakker** [comment]
That's perfect. I think that should fix it.
