### ISSUE TITLE
Full HDFS persistence support (read/write)

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#23]
Currently HDFS persustence factory can only write the lineage data off to a file, but never read it back. To fully make use of this type of persistence we need to be able to read and parse the written lineage JSON to be able to link it with the descendant lineages and visualize in the Spline UI.

**Comment by GeorgiChochov** [comment]
The ability to persist lineage offline and import it after the fact would be quite useful. 
I know you have ideas for how to expand on this, @wajda.

**Comment by wajda** [comment]
We could export/import the lineage.
Imaginary example:
1. I have a file `A` on HDFS, and its lineage in Spline
1. I want to copy `A` to a different infrastructure (network, cluster, cloud, you name it), monitored by another independent Spline instance. And I don't want to loose the lineage of `A`
1. Using Spline UI or CLI I dump `A`'s full lineage to a file and carry it with `A` to a new infrastructure
2. There the lineage dump can be imported manually (again by using UI or CLI), or even automatically on the first Spline tracked read from `A`.

**Comment by wajda** [comment]
Superseded by #815 and AbsaOSS/spline-spark-agent#156
