### ISSUE TITLE
Add package-lock.json to VCS

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#237]
## Issue
After `git clone ...` and `mvn clean install ...` I am left with an unstaged change to the repository. This is due to the npm's generated `package-lock.json` and it not being in the `.gitignore`.

Please add `web/ui/package-lock.json` in some form.

## Working with ...
- ... branch: Develop
- ... commit: [54009bd](https://github.com/AbsaOSS/spline/commit/54009bd2d8a2df0daa59f8464be007cf1ee7122c)

**Comment by wajda** [comment]
Actually, the `package-lock.json` is supposed to be added in the VCS in addition to the `package.json`
https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8
