### ISSUE TITLE
REST exception handler seems to be broken

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#265]
@algattik commented 2 Jun 2019, 15:59 CEST
> In addition, the REST exception handler seems to be broken, the original exception is swallowed and this gets logged instead (at least in the context of #263):
> 
> ```
> Jun 02, 2019 1:51:21 PM org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver doResolveHandlerMethodException
> WARNING: Failed to invoke @ExceptionHandler method: public org.springframework.http.ResponseEntity<java.lang.String> za.co.absa.spline.web.rest.controller.RESTErrorControllerAdvice.handle_500(java.lang.Throwable)
> java.lang.IllegalStateException: getWriter() has already been called for this response
> 	at org.apache.catalina.connector.Response.getOutputStream(Response.java:644)
> 	at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:196)
> ```

**Comment by wajda** [comment]
I cannot reproduce it. Tried both `.war.` and `.exec.jar`, and logs look correct:

```
11:49:03.368 [http-bio-8080-exec-8] ERROR za.co.absa.spline.web.logging.ErrorCode$ - ErrorCode(b61d2a5c-fe86-4049-ab5f-3f26e4dd5229)
java.lang.RuntimeException: class za.co.absa.spline.model.op.Write requires value for 'path'
        at scala.sys.package$.error(package.scala:27)
        at salat.DefaultArg.safeValue$lzycompute(Grater.scala:484)
        at salat.DefaultArg.safeValue(Grater.scala:480)
        at salat.ConcreteGrater.safeDefault(Grater.scala:435)
        at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
        at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
```

**Comment by algattik** [comment]
Might be. As I mentioned, I only saw this behavior in the context of #263.

**Comment by wajda** [comment]
Ok, so it seems to be another corner case then. Unfortunately the team is currently fully focused on 0.4 development and we have no capacity to continue supporting 0.3 especially for supporting different corner cases and technology combinations.
So I'm marking it as "help needed" letting the community to address this issue.
