### ISSUE TITLE
Spline missing sources lineage when jdbc is used as sink

### ISSUE THREAD

**Issue by lekyag** [AbsaOSS/spline#267]
Entire lineage is not displayed in spline UI when JDBC is used as sink.
![image](https://user-images.githubusercontent.com/44967106/59025833-aa84f400-8872-11e9-8295-903de7dbd6ff.png)

While using HIVE as sink, entire lineage is displayed as i wished.
![image](https://user-images.githubusercontent.com/44967106/59025983-0b143100-8873-11e9-894f-4aa93249b100.png)

I am expecting sources lineage also, while using jdbc as sink.

So, Can anyone please help me regarding this. Thanks in advance

**Comment by wajda** [comment]
If I understand correctly the problem seems to be in reads, not write. 
Can you share your spark script please?

**Comment by manthanthakker** [comment]
Are you able to see the detailed lineage? For me too, when the source is SQL the detailed lineage is blank.

**Comment by wajda** [comment]
Guys, we have not enough resources to support Spline 0.3 at the moment. I'll appreciate if somebody is up to help fixing this one. Thank you.
