### ISSUE TITLE
Simplify the arango storage model

### ISSUE THREAD

**Issue by leborgneromain** [AbsaOSS/spline#273]

**Comment by leborgneromain** [comment]
Note for the dev : Some entities might not need the _key and only the ones that actually need it can define it as non optional attribute.

**Comment by wajda** [comment]
Because of the storage model discrepancy between two different PRs with the regard to `Schema`, the persister, migrator and the consumerb need to be fixed according the the selected model.

**Comment by wajda** [comment]
> Because of the storage model discrepancy between two different PRs with the regard to `Schema`, the persister, migrator and the consumerb need to be fixed according the the selected model.

this will be fixed in #301
