### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by aliscodecraft** [AbsaOSS/spline#274]
Hello, upon running the following command :

 spark-shell --packages "za.co.absa.spline:spline-core:0.3.5,za.co.absa.spline:spline-persistence-mongo:0.3.5,za.co.absa.spline:spline-core-spark-adapter-2.3:0.3.5"

I run accross the following error message which is seemingly related to spark-shell not being able to retrieve spline dependencies from the target servers, explicitely has to do with the absence of the proper certificate. Is there a way to skip certificate validation ? Would like to emphasize that I have access to the net and I'm able to wget the `jars` no problem. Since I'm planning to use Spline to cover my data science project's data lineage aspect, would anyone be as kind as to point me to hints to resolve this issue  please?

<img width="947" alt="Capture" src="https://user-images.githubusercontent.com/39502249/59608095-ed698600-9114-11e9-8b53-1023932ce4bd.PNG">

**Comment by wajda** [comment]
It doesn't seem to be related to Spline. For some reason your Spark JVM doesn't trust _maven.org_ SSL cert.
Does it happen with Spline artefacts only? Isn't it a coincidence? Can you try to resolve any other random maven artefact that is not cached in your local maven repo or perhaps in your Nexus?

**Comment by wajda** [comment]
By the way, Spline 0.3.5 is old. Please use version 0.3.8

**Comment by aliscodecraft** [comment]
Hello, thank you so much for taking the time to address my issue and  sorry for the late reply. 

I tried the 0.3.8 version but that didn't solve the problem. 

I wanted to try spline on another computer, followed a tutorial that instructed to issue the following command in order to  test a sample scala job for data lineage visualization, it showed another error related to dependencies. Would you happen to have any clue as to what might be wrong ?

`mvn test -Psamples -Dspline.mongodb.url=mongodb://localhost -Dspline.mongodb.name=local -DsampleClass=za.co.absa.spline.sample.SampleJob1`


<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/39502249/59685390-58ca5b00-91dc-11e9-8cd4-04140a9e8f30.PNG">


I also did try 0.3.8 on my other computer but ended up being incapable to retrieve another dependency, I'm having quite of a problem understanding where does this come from.

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/39502249/59688549-3afdf580-91de-11e9-9beb-8202ba55ec1c.PNG">

**Comment by wajda** [comment]
Wait, are you using SBT? If so then it seems to be a SBT bug. We have a similar bug report here - #160 

Regarding 0.4.0-SNAPSHOT, it's not ready yet, it's under development. Wait two weeks.

**Comment by liamlyne** [comment]
@wajda any updates on 0.4.0?

**Comment by wajda** [comment]
soon...  We're aiming at the end of July / beginning of August. Unfortunately we are under-resourced and it's a holiday time. But we are hard working on it, so please stay tuned.
