### ISSUE TITLE
Lineage overview for Menas

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#291]
Create a Consumer REST resource for getting a lineage overview by a file path and a spark job id
Create a UI for the lineage overview
Create a UI routing to open a lineage overview page directly by providing a URL with those two parameters

**Comment by wajda** [comment]
@GeorgiChochov

**Comment by wajda** [comment]
@benedeki

**Comment by wajda** [comment]
@GeorgiChochov

**Comment by wajda** [comment]
@leborgneromain

**Comment by wajda** [comment]
As discussed, we need to decouple Spline from Menas and instead of providing a Menas specific UI or REST we'll provide generic API to cover Menas needs.
In particular we agreed:
1. Do not use ~`applicationId`~ anywhere in Spline API unless it is absolutely necessary and  justified by some generic use case. Instead `eventId` or `execId` should be used where appropriate.
1. In the Lineage Overview page URL instead of ~`path`~ and ~`applicationId`~ paramaters use `eventId` as the primary and only identifier of a high-level lineage graph to be displayed. I.e. the Overview page displays a lineage of a given _write_ to a given _data source_ at a given _time_.
1. Create a Consumer REST resource to look up for events by a sample object and other generic criteria. Menas will use this resource to resolve an `eventId` by `appId` and `path` on their end. Example: (either GET or POST) ```/consumer/execution/event/_search?sample={extra:{appId:1234567890}}&destinationPath=....```

**Comment by GeorgiChochov** [comment]
Sounds reasonable

**Comment by benedeki** [comment]
Sounds as what we agreed upon 😉

**Comment by wajda** [comment]
@benedeki Could you please close this as soon as you are happy with the integration results

**Comment by wajda** [comment]
Closing this as REST API and Webjar have been proven working. Some client side issues popped out during testing, but they don't seem to be related to this particular use case, and hence should be reported separately.
