### ISSUE TITLE
Spark Lineage is not triggered if the action is not "save","saveAsTable" or "insertInto"

### ISSUE THREAD

**Issue by rbharath24** [AbsaOSS/spline#304]
Spark lineage is not triggered if the action is not one of "save", "saveAsTable" or "insertInto". We have a query frontend that submits queries for execution into spark sql. I would like to understand if there is are any reasons behind this decision making?

**Comment by wajda** [comment]
What action do you want to track the lineage for?

**Comment by wajda** [comment]
Answering your question, well, strictly speaking there was no specific reason. But capturing and other action execution plans didn't make much sense from the perspective of the main Spline's goal - tracking end-to-end lineages, i.e across the boundary of individual Spark jobs. From that perspective capturing lineage only makes sense when the data transformation result was persistent. If another job reads that data and produce another persistent result Spline is able to join both lineages, and so forth.

**Comment by rbharath24** [comment]
Sure. Perfect. I believe this puts things into proper perspective for us. Thanks for the clarification.
