### ISSUE TITLE
Make sure table identifier is properly constructed

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#306]
class `WriteCommandParserFactoryImpl`
```scala
  private def createTableWrite(table: CatalogTable) = {
    val identifier = table.storage.locationUri match {
      case Some(location) => location.toURL.toString
      case _ =>
        val codec = new URLCodec()
        URIPrefixes.managedTablePrefix +
          codec.encode(clusterUrl.getOrElse(throw new IllegalArgumentException("Unknown cluster name."))) + ":" +
          codec.encode(table.identifier.database.getOrElse("default")) + ":" +
          codec.encode(table.identifier.table)
    }
    identifier
  }
```
Here `clusterName` is actually a Spark master URL. Using it as a part of unique table identifier seems incorrect.

**Comment by lukasnalezenec** [comment]
Hi, this behaviour is intentional.

**Comment by wajda** [comment]
However it is incorrect. Spark master URL can vary depending on how you run your Spark job. Hence it cannot identify a cluster, by definition.

**Comment by wajda** [comment]
Related to #21 
One of the important consideration about the format of a table unique identifier is the data catalog structure:
- What if the catalog database name is changed between the logically connected jobs? Or the opposite, what if logically unrelated jobs refer the same database and table names from the physically separated catalogs (different Hives, machines, etc).
- What if a table is backed by a parquet file that is also accessed directly from another job.

**Comment by wajda** [comment]
To solve the aforementioned problem with uniqueness of the table identifiers we can simply "dereference" them and use the warehouse URI as a table URI. Then the problem boils down to only guaranteeing the uniqueness of the data warehouse locations in the scope of Spline monitored cluster. That we can leave on the user's responsibility.
