### ISSUE TITLE
Spline with Hbase

### ISSUE THREAD

**Issue by zackmeso** [AbsaOSS/spline#32]
Hello,
I just tested spline with mongodb and it works like a charm. 
However, I wonder if there's going to be a support for Hbase? What do we need in order to make spline support other dbs such as Hbase?

**Comment by wajda** [comment]
Hi Zakaria,
As for the lineage persistent, our ultimate goal is to make Spline as much storage type agnostic as possible and practical. That said, although there is no HBase storage implementation for Spline at the moment, it likely could be added in the future. Spline project is being actively evolved and so does the storage API.
If you wish to implement your own lineage storage (HBase or anything else) it should be easily accomplished by inheriting from ```PersistenceFactory``` abstract class.
We will be happy to answer any questions and will appreciate pull requests.
