### ISSUE TITLE
Upgrade to ArangoDB 3.5

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#332]
https://www.arangodb.com/docs/stable/release-notes-upgrading-changes34.html
https://www.arangodb.com/docs/stable/release-notes-upgrading-changes35.html

Test case:

This
```shell
curl 'http://localhost:8888/consumer/executionEvent?timestampStart=1567177906330&timestampEnd=1567264306330&sortName=timestamp&sortDirection=asc&searchTerm=&offset=0&asAtTime=1567177906396'
```
should return
```json
{"elements":["ExecutionEvent;",[]],"totalCount":0,"offset":0,"size":10}
```
Specifically `"totalCount":0`

**Comment by leborgneromain** [comment]
After investigation it seems that the bug was introduced during the Harvester refactoring : 
https://github.com/AbsaOSS/spline/issues/365
