### ISSUE TITLE
How to search Spark job by timestamp from Spline web UI tool?

### ISSUE THREAD

**Issue by iamgzy** [AbsaOSS/spline#336]
I know the issue board should be used for submitting tickets, so please forgive me if I am using this thread as StackOverflow for Q/A purpose (is there a different channel to ask instructions regarding Spline?).

Now I am able (Thanks to @wajda !!) to pull sample lineage information via Spline web UI tool(spline-web-0.3.9-exec-war.jar), how can I search lineage job information by submit timestamp? Current version seems only support search by keyword. However if I ran same sample job for 20 times then it will generate duplicate lineage information. 

Another scenario is when define table name as Scala function parameters then each time when run the spark job the result may vary. But however it will be very difficult to search the lineage information if only by keyword... 

So is there an existing function available or something to offer in the future?

Thanks

**Comment by wajda** [comment]
In Spline 0.3 search is done on the following fields: `appId`, `appName`, `path` (case insensitive substring inclusion) and `datasetId` (full match). I think you can use `appId` (corresponds to Spark app ID) to identify the particular job.

As for the future improvements, yes, we will definitely be adding more search functionality. After stabilizing Spline 0.4 (which is almost a complete rewrite) we'll focus more on widening feature coverage. Better search we'll likely be added in Spline 0.5.

**Comment by iamgzy** [comment]
@wajda Thanks again wajda

What if run same spark job for 10 times but try to pull the lineage for spark job on certain timestamp
Does current version (0.3) support any search by timestamp? Also could you please elaborate about the appID search in the Spline Web UI?

**Comment by wajda** [comment]
No you can't search by timestamp. 
Regarding app IDs, try `curl http://localhost:4040/api/v1/applications`
You'll see a list of executed jobs, e.g.:
```js
[ {
  "id" : "local-1567522567878",
  "name" : "Spark shell",
  "attempts" : [ {
    "startTime" : "2019-09-03T14:55:56.933GMT",
    "endTime" : "1969-12-31T23:59:59.999GMT",
    "lastUpdated" : "2019-09-03T14:55:56.933GMT",
    "duration" : 0,
    "sparkUser" : "wajda",
    "completed" : false,
    "appSparkVersion" : "2.4.4",
    "endTimeEpoch" : -1,
    "startTimeEpoch" : 1567522556933,
    "lastUpdatedEpoch" : 1567522556933
  } ]
} ]
```
`local-1567522567878` is a Spark app ID. You can search by it.

**Comment by iamgzy** [comment]
Thank you. Hope there is time stamp search in the new release.
