### ISSUE TITLE
Spark 2.1 support

### ISSUE THREAD

**Issue by iamgzy** [AbsaOSS/spline#355]
Hi, our current system come with Spark 2.1. So just wondering is there still support from Spline for Spark 2.1?

from maven repo looks like there is only adapter for spark 2.2, 2.3 & 2.4, there is none for 2.1

>spline-core-spark-adapter-2.2
>spline-core-spark-adapter-2.3
>spline-core-spark-adapter-2.4

Then what is the possible solution to get Spline & Web UI tool working with Spark 2.1?

Found [issue#49](https://github.com/AbsaOSS/spline/issues/49) related to the same question but not sure how much has changed since then

Thanks in advance

**Comment by wajda** [comment]
I didn't try it, but as Marek explained #49 it will hardly work because of incomplete or missing listeners in Spark SQL 2.1
