### ISSUE TITLE
A sample spline-atlas example

### ISSUE THREAD

**Issue by amalkurup** [AbsaOSS/spline#36]
Can you guys please upload a sample spline-atlas example/demo on github. It would be very useful

**Comment by mn-mikke** [comment]
The [documentation](https://absaoss.github.io/spline) contains a section describing how to set up a basic configuration of persistence to Atlas. Do you miss there anything important?

The sample sub project contains several spark sample jobs. When you set up the underlying persistence layer to Atlas. You can utilize these sample jobs as well.

**Comment by amalkurup** [comment]
An explanation similar to mongodb persistence, along with screenshots would really help

**Comment by vackosar** [comment]
There is little bit more in the doc section now. Can u check it and reopen this if it is still not enough?
