### ISSUE TITLE
Missing edges in the harvester lineage creation

### ISSUE THREAD

**Issue by leborgneromain** [AbsaOSS/spline#365]
Some of the edges between operations nodes are missing after the creation of them by the harvester.  Using the migration tool create the graph connections correctly. 

It seems that some children ids are missing when the harvester collect the data. The bug might have been introduce during the refactoring of the harvester in this PR : https://github.com/AbsaOSS/spline/pull/311

**Comment by wajda** [comment]
Confirm a bug in a Harvester
