### ISSUE TITLE
How to integrate the spline with pyspark

### ISSUE THREAD

**Issue by anveshbhimavarapu** [AbsaOSS/spline#374]
Is MangoDB must for spline to run and store the lineage information on HDFS, or can this be store the information with out mangoDB. If so what would be the process 

Tried with out running the web jar as I have no environment with mangodb but used hdfs in persistence factory, can not see any lineage file being generated on hdfs 

Quick help is much appreciated 

Anvesh

**Comment by wajda** [comment]
Hi Anvesh,
Spline 0.3 UI requires lineage metadata to be store in MongoDB. In fact MongoDB is the only full-featured storage available out of the box. HDFS is mostly designed for logging and debugging purposes. It can also be used for integration with custom developed 3rd party tools, but the lineages stored on HDFS in order to be full lineages (i.e. linked with the previous related jobs lineages etc) a MongoDB persistence still has to be enabled. For example, you may enable composite persistence factory to use both Mongo and HDFS persistence at the same time.

**Comment by anveshbhimavarapu** [comment]
Hi wajda, 
Thank you now I have an environment with mongodb,have used persistnce with mongodb but was not able to see any lineage graph over webUI no tables have been loaded either in mangodb database,used spark bundle 2.2 and webUI 0.3.9-war.jar 

Given the setting under —java.extra.options 
Please let me know if I am missing anything 

Anvesh

**Comment by wajda** [comment]
Did you mean _spark.driver.extraJavaOptions_?

**Comment by anveshbhimavarapu** [comment]
No passing them through driver-java-options and spline.mode is given as required, there are no errors as well but can not see any tables or lineage from the web

**Comment by anveshbhimavarapu** [comment]
Passing the spline fat jar through the — conf spar.driver.extraclasspath

**Comment by wajda** [comment]
Are you using codeless initialization?
Can you please post your config files and command line that you use?

**Comment by anveshbhimavarapu** [comment]
Using code base for python and the using 
Spark-submit — deploy-mode client —conf spark.driver.extraclasspath=/tpt/spline.jar — driver-java-options=“-Dspline.mode=REQUIRED -Dspline.mongodb.url=mongodb://id/dB -Dspline.persistance.composit.factory=mongodb,hdfs persistence from spline Doc -Dspline.url=localhost/Portno -Dspline.hdfs.file.name=hdfs:///path on hdfs -Dspline.hdfs.file.permisions=777” test.py

**Comment by wajda** [comment]
Can you please share `test.py` file?

**Comment by anveshbhimavarapu** [comment]
below is the code snippet 

try:
    import pyspark
except:
    import findspark
    findspark.init()
    import pyspark

import sys

from pyspark.sql import sparkSession

# import spark session from the below class with all the parameters
class Run(SparkContext):

    sc._jvm.za.co.absa.spline.core.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)

    df=spark.sql("""select * from db.users""")

    df1=spark.sql("""select * from db.sales""")

    df2=df.join(df1,['id'],inner)\
            .groupBy('id').agg(sum('sales_amount').cast("decimal(38,4"))

    self.table_store(df2,'db.users_sales')

**Comment by wajda** [comment]
Thanks Anvesh. Can I also take a look at `self.table_store(...)` method? I'm interested in the Spark method you actually call to store the final result.

**Comment by wajda** [comment]
Ah Ok, `createOrReplaceTempView` method is not supported by Spline yet. Unfortunately Spline 0.3 is EOL, so we don't plan any further improvements in it. Will see if we can quickly add support for this method into the upcoming Spline 0.4, or to one of the next releases otherwise.

**Comment by anveshbhimavarapu** [comment]
Wajda, thank you for the insight, what all are the currently supported options for tracking lineage using Spline. and is there any document which can give more insight on spline

**Comment by wajda** [comment]
This is all docs that we have at the moment - https://absaoss.github.io/spline/ Plus some blogs.
Making better documentation is on our todo list.
Regarding the supported Spark actions, in Spline 0.3 the `DataFrameWriter` methods are supported (the ones you call via `df.write....`)
Spline 0.4 also adds support for some basic DDL/DML queries invoked via `sparl.sql(...)` method, e.g. `DROP TABLE`, `CREATE AS SELECT`, `INSERT INTO TABLE` and some others. The work on this is still in progress, so more stuff will come in the future.

**Comment by anveshbhimavarapu** [comment]
Thanks Wajda, I have tried replacing the method with df.write.parquet(‘location’)
The files are created in the hdfs location but the lineage is not being tracked getting below error 

Py4j.protocol.py4jjavaerror: an error occurred while calling o508.parquet
:java.lang.noclassdeffounderror: .org/apache/spark/sql/catalyst/catalog/hivetablerelation

**Comment by cerveada** [comment]
Hi Anvesh,
Spark 2.2.x actually doesn't publish lineage for hive, it only provides it for writes in this form:```dataFrame.write.x```. 

If you use Spark 2.3+ with spline the lineage for hive should work fine.

I'm not sure what causes the exception from your last message.
