### ISSUE TITLE
Nifi generated Atlas lineage is not recognized by Spline Spark as Input 

### ISSUE THREAD

**Issue by smunigati** [AbsaOSS/spline#39]
When we use Nifi and capture the lineage in Atlas  qualifiedName is formatted as "filepath@clustername"  which is not further recognized by Spline as HDFS Input for further processing . 

spline/persistence/atlas/src/main/scala/za/co/absa/spline/persistence/atlas/conversion/DatasetConverter.scala , need to support dynamically passing as arguments so that we can take out  absolute path and add `@cluster`  in the end.  

Something like below .. 
```scala
def convert(operations: Seq[op.Operation], datasets: Seq[MetaDataset], attributes: Seq[Attribute]): Seq[Dataset] = {
  val attributeMap = attributes.map(a => a.id -> a).toMap
  for {
    operation <- operations
    dataset <- datasets if dataset.id == operation.mainProps.output
  } yield {
    val name = operation.mainProps.name + datasetSuffix
    val qualifiedName = dataset.id
    val attributes = dataset.schema.attrs.map(i => AttributeConverter.convert(qualifiedName.toString, attributeMap(i)))
    val translated = operation match {
      case op.Read(_, st, paths) =>
        val path = paths.map(_.path) mkString ", "
        val clustername = System.getProperty("cluster.name")
        val absolutebasepath = System.getProperty("absolute.base.path")
        val upath = path.replace(absolutebasepath,"")
        new EndpointDataset(name, qualifiedName, attributes, new FileEndpoint(upath, upath+"@"+ clustername), EndpointType.file, EndpointDirection.input, st)
      case op.Write(_, dt, path, _) => new EndpointDataset(name, qualifiedName, attributes, new FileEndpoint(path, path), EndpointType.file, EndpointDirection.output, dt)
      case _ => new Dataset(name, qualifiedName, attributes)
    }
    attributes.foreach(_.assingDataset(translated.getId))
    translated
  }   
}
```

**Comment by vackosar** [comment]
- Can you be more specific what you mean by: "not further recognized by Spline as HDFS Input for further processing". E.g. can provide an example?
- If this is question about modification of persistence for Atlas, then can you provide some links to documentation for us to review. My concern is that your use case is too uncommon and non standard. In that case it shouldnt be a problem to implement your own Atlas persistence layer and just configure it in Spline without needing to make it part of Spline repository.

**Comment by vackosar** [comment]
@smunigati I can see that you created custom formatting for NiFi for HDFS URLs described here: https://community.hortonworks.com/articles/186772/end-to-end-atlas-lineage-with-nifi-spark-hive.html

**Comment by wajda** [comment]
Closing as obsolete. Atlas integration has been removed from the Spline core - #279
