### ISSUE TITLE
Spline dependencies

### ISSUE THREAD

**Issue by ckeenlim** [AbsaOSS/spline#392]
Hello spline team, giving this project a try but it seems like I'm missing some dependencies despite adding the bundle to my dependencies. Using spark-2.3-cloudera, spline-bundle-2.3. I'm creating a fat/uber jar with all deps and running the spark job on prem. 
Exception: classnotfound com.databricks.spark.xml.XmlRelation

**Comment by wajda** [comment]
Hi @ckeenlim ,
Looks like you are missing `com.databricks:spark-xml` package.
Spline is tested on vanilla Apache Spark, so it could be possible that certain dependencies are missing in other distributions.

**Comment by ckeenlim** [comment]
Thanks! Scala compiler was also missing so I had to include it but adding the databricks library did make the trick. This is awesome!
