### ISSUE TITLE
UI doesn't show any error when Consumer is inaccessible

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#405]
When Consumer is not running XHR response status code is 0, and it apparently either isn't caught by our error handler, or is interpreted differently. No error is shown on UI and everything looks like there's just no data.  

![image](https://user-images.githubusercontent.com/795479/67307998-b7407680-f4f9-11e9-85d6-a35c5e8259e6.png)

**Comment by Zejnilovic** [comment]
LGTM
