### ISSUE TITLE
Migrator cli - add validations

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#406]
- [ ] -r file must exist
- [ ] -l loglevel is one of `ALL`, `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`
- [ ] -e file should not exist -> This is mainnly because I don't see a feature of removing from file what has already been "recovered"

**Comment by Zejnilovic** [comment]
scopt generally doesn't have validations. Maybe do a scopt-wide update?

**Comment by wajda** [comment]
Since we removed Migrator tool from 0.5 I'll move the changes to 0.4 branch. If we need to do other fixes in Migrator we'll either do it in 0.4.x or even extract it as a separate project.
