### ISSUE TITLE
Incorrect total count on the dashboard

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#409]
The total count of jobs on the dashboard is limited to 100.
If I'm looking for a job that doesn't fall into this bucket then the job isn't found.

Example:

![image.png](https://images.zenhubusercontent.com/5c04fd55820d8748e06666cd/8a29f8c2-320d-4b33-8fc4-97ac02db52fa)

**Comment by Zejnilovic** [comment]
In case I ran new jobs that made lineage and I press the go to the beginning of a list, the count will drop by the number of new destinations written. So old ones are removed new ones are not added.

**Comment by wajda** [comment]
@Zejnilovic 
> In case I ran new jobs that made lineage and I press the go to the beginning of a list, the count will drop by the number of new destinations written. So old ones are removed new ones are not added.

Can you please retest it on Develop?

**Comment by wajda** [comment]
> In case I ran new jobs that made lineage and I press the go to the beginning of a list, the count will drop by the number of new destinations written. So old ones are removed new ones are not added.

@Zejnilovic Could you please retest this and close the issue if it works?

**Comment by Zejnilovic** [comment]
> > In case I ran new jobs that made lineage and I press the go to the beginning of a list, the count will drop by the number of new destinations written. So old ones are removed new ones are not added.
> 
> @Zejnilovic Could you please retest this and close the issue if it works?

I would say this is ok since there is no page limit and no automatic refresh of jobs.
