### ISSUE TITLE
When rest gateway can't connect to Arango, misleading error in UI

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#410]
When the rest gateway can not connect to Arango db there is only warning in rest gateway log and then after 2 minutes an error in log and in UI console on the user side which doesn't tell anything. Picture bellow.

![image](https://user-images.githubusercontent.com/17467768/67365400-1dacaf80-f561-11e9-957d-4eeee9bd31c7.png)

## Expected behaviour
-  get a warning in both rest gateway log and console
- after two minutes get a proper error in console.

**Comment by cerveada** [comment]
Neither me nor Romain was able to reproduce this issue. It seems like it was fixed by #405. 
- The error appears as UI pop-up in few seconds
- The error is logged in harvester log
- The error is logged in Browser log

**Comment by wajda** [comment]
As further discussed the issue can occur in some networks, and also in a case of long running DB query.
We need to accommodate for timeouts.
Let's move it to 0.5

**Comment by wajda** [comment]
related to #485

**Comment by wajda** [comment]
closed in favor of #712
