### ISSUE TITLE
UI - Turn from live data to range selection and back doesn't reset the selection

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#412]
When I go from `Live Data` to `Range Selection`, select date and then back to `Live Data`. My selection remains the same. I would expect it to reset.

![image](https://user-images.githubusercontent.com/17467768/67385716-e0154a00-f593-11e9-9bec-e7b34d2fbfa0.png)

**Comment by Zejnilovic** [comment]
And the `go back` doesn't work, so I need to refresh the page.

**Comment by wajda** [comment]
#440 changed the concept of "Live / Range" switch. Now it's just a "by date" filter.
![image](https://user-images.githubusercontent.com/795479/68978150-450e3980-07fa-11ea-9686-0f0039cffb61.png)
The table is refreshed accordingly on every change in the state.
