### ISSUE TITLE
UI Range Selection - always resets the selection

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#413]
I would want to move the date by one day, or something similar, but I always have to start by click 1st time for the beginning of the range and 2nd time for the end of the range. And thanks to it having two windows displayed it looks like left one is to change the start and right one is to change the end.

![Oct-23-2019 12-55-03](https://user-images.githubusercontent.com/17467768/67386046-8a8d6d00-f594-11e9-8a26-a378278c78f5.gif)

**Comment by Zejnilovic** [comment]
Maybe add a feature to be able to select even from the back to the front, since what you see first is today's date and you usually then want to go backwards.

**Comment by wajda** [comment]
I assume this one is solved in Spline 0.4.0
![image](https://user-images.githubusercontent.com/795479/70187567-d6344a00-16ee-11ea-9de8-7eff65602cab.png)

Closing the issue.
