### ISSUE TITLE
Update copyrights from 2017 to 2017-2019

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#414]
Update copyrights from `2017` to `2017 - 2019`. Even more so if you are officially releasing.

---
There is a shortcut in IntelliJ IDEA you just have `2017 - $today.year`

**Comment by wajda** [comment]
Ok we can. But I wonder what difference it makes.

**Comment by Zejnilovic** [comment]
We agreed on different approach at CQC. Closing this.
