### ISSUE TITLE
Range selection sends a network request every time someone click on something

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#416]
Every time I click on any "button" in range selection there is a network request, which then returns all the data. This means even if I change the minutes counter once, I get back everything again, even if there is no change.

This might not pass the test of big load. Maybe implement a search/find button to confirm the selection?

**Comment by wajda** [comment]
Yep, we need to debounce it.
I'd say it's an enhancement, not a bug.

**Comment by wajda** [comment]
There will be new UI for Spline
