### ISSUE TITLE
Lineage data schema document

### ISSUE THREAD

**Issue by iamgzy** [AbsaOSS/spline#438]
Hi Spline team, can any one please provide a schema document (whatever format) for the back end data store?

I understand the lineage data can be stored in Mongo, HDFS or Hbase(Atlas), so there must be a general schema for the column-based lineage data regardless of data store implementation. Or may be just extracted from json data file from any above NoSQL datastore?

We are interested in querying the data or may be merged them into our central store, so just wondering where can find the schema doc so we can build the mapping/merging procedure.

**Comment by wajda** [comment]
There is no universal persistence schema. Every type of persistence has different format and it's responsibility of the DataLineageReader and DataLineageWriter to load and save lineage data respectively.  The lineage object model that is shared between the layers is defined here -   
https://github.com/AbsaOSS/spline/tree/release/0.3.9/model/src/main/scala/za/co/absa/spline/model

Also, if you want to dig that deep into Spline would encourage you to take a look at 0.4 more closely. It will be released in days. It has completely different graph-based storage format and another approach to integration with 3rd-parties by exposing set of dedicated APIs.
