### ISSUE TITLE
unable to mvn install -DskipTests

### ISSUE THREAD

**Issue by sukumaar** [AbsaOSS/spline#44]
Getting Error while `mvn install -DskipTests`. I am already having : JDK 8+ Maven 3.0 Node.js 6.9 
But still getting error as 

> dependencies.dependency.version' for org.apache.spark:spark-core_2.11:jar must be a valid version but is '${spark.version}'

**Comment by wajda** [comment]
Please add `-Pspark-2.2` parameter. All fix it in the documentation. Thanks.

**Comment by sukumaar** [comment]
Thanks, It is working fine.
