### ISSUE TITLE
UI: "Live / Range" switch doesn't refresh the table

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#440]
1. When I switch to a date range mode the table still shows the same content, but the default date-range is set to `now+1d` which doesn't correspond the data displayed
1. I select some arbitrary dates, the tables refreshes OK. But then when switching back to "Live" nothing happens with the table. It doesn't refresh until I change any other filter.
1. When switching to the "range" mode for the 2nd time, the previous range is still there, but the table is again not updating.

**Comment by Zejnilovic** [comment]
Seems similar #412
