### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#444]
![image.png](https://images.zenhubusercontent.com/5c04fd55820d8748e06666cd/d72e0f64-9010-42e0-9553-245358d4cd9d)

1. Missing application header with name and logo. Current Spline logo position is unclear.
1. "Show attributes graph" switch is misleading.  Let's rename to "Show attribute schema diagram" and move it to the right.
1. Orange buttons are too accented. 
1. Orange boards are too accented. Let's make them thinner or remove completely.
1. Corners are too round.
1. For some "Project" operations the "Transformations" section is empty. If there is nothing to show in the section it should either stated in words (e.g. "no transformations") or the section should be hidden. Otherwise it looks like a bug.
1. On the schema tree complex types are prefixed with ">" and indented on left hand side. It makes them visually look like sub-attributes of a previous simple type. Please either fix indentation or remove a chevron.
1. Arrays of simple types looks expandable, but do not actually expand.
1. Missing page title for detailed lineage.

**Comment by Zejnilovic** [comment]
If I may, number **2**, the button all in all does not look like it is the part of the selection but something general like `Dashboard`. Can we move it into the frame or something?

Suggestion for **10**, In the detail of the node, at the bottom there seems to be always an "overflow", like it is not ending but there is no scroll, looking like the user might be missing some information. Could it be rounded before?
