### ISSUE TITLE
Spline Properties Mongodb URL

### ISSUE THREAD

**Issue by sanjurm16** [AbsaOSS/spline#45]
At the moment, the mongo url is saved in the spline properties. In case ther is a user and password for the mongo db, The password need to be saved in the mongodb url property as plain text. This must be improved to allow for some sort of encryption.

**Comment by vackosar** [comment]
I think we should also provide option to read these from environmental variables. Right now you can still do that passing them through jvm props:
```
    -Dspline.persistence.factory=${USER}:${PASS}@... 
```

I don't think most of other programs provide other options. Do you have any other suggestion?

**Comment by wajda** [comment]
How would you solve this issue? I don't think there is a way to make it properly secured on a shared server box. Even if you encrypt a password the server need to decrypt if somehow on the startup, so there must be anyther password stored somewhere in a plain text and so on. I would say that securing MongoDB connection should be done on other than app levels. E.g. encrypted hard drive, secured network or other authentication methods that don't involve sending a plain text passphrase to the server.
