### ISSUE TITLE
Attribute highlighting - UI

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#451]
Implement functionality in UI that will highlight Attribute lineage for selected attribute.

**Comment by wajda** [comment]
After trying out a few prototypes the following solution seems if not the most intuitive, but at minimum the least controversial. 

The attribute highlighting will consist of two parts - the lineage and impact of the selected attribute.
The _lineage_ part starts at sources and ends at the node where the given attribute is created. The _impact_ part starts at the node at which the _lineage_ part ends and goes down the graph. The part of the impact that consists of nodes containing the selected attribute will be visually distinguish (bold) from the other highlighted nodes.
The nodes and paths that aren't highlighted will be faded.

**Optional**: the path from the selected node to the attribute origin (or to the root sources?) could be visually emphasized as well.
