### ISSUE TITLE
Could not resolve dependencies for project org.webjars:absaoss-spline-client:jar:0.4.0-SNAPSHOT: Could not find artifact za.co.absa.spline:client-ui:zip:dist:0.4.0-SNAPSHOT in java-velocypack-module-scala-mvn-repo

### ISSUE THREAD

**Issue by kaustubhghode** [AbsaOSS/spline#454]
After Running the spline project (https://github.com/AbsaOSS/spline) in Eclipse(with scala support),
I am getting the following error.
{Could not resolve dependencies for project org.webjars:absaoss-spline-client:jar:0.4.0-SNAPSHOT: Could not find artifact za.co.absa.spline:client-ui:zip:dist:0.4.0-SNAPSHOT in java-velocypack-module-scala-mvn-repo (https://raw.githubusercontent.com/wajda/java-velocypack-module-scala/mvn-repo/)}.

what are the steps needed to run the spline project.

**Comment by wajda** [comment]
Try to run a full Maven build first
```shell
mvn install -DskipTests
```

**Comment by kaustubhghode** [comment]
Thanks for replying,
after running mvn install -DskipTests, I am getting the following error in rest-gateway.
[ERROR] around Ant part ...<exec failonerror="true" executable="cmd" osfamily="w
indows">... @ 5:64 in D:\spline-develop\spline-develop\r
est-gateway\target\antrun\build-main.xml

**Comment by wajda** [comment]
There should be more information about the error in the logs. Can you provide a complete output?

**Comment by kaustubhghode** [comment]
This the complete error which i am getting.

[INFO] Executing tasks

main:
     [echo] installing redoc-cli
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spline ............................................ SUCCESS [8:35.040s]
[INFO] commons ........................................... SUCCESS [10:50.363s]
[INFO] producer-rest-model ............................... SUCCESS [7.068s]
[INFO] spark-agent ....................................... SUCCESS [13:16.443s]
[INFO] migrator-tool ..................................... SUCCESS [3:02.107s]
[INFO] rest-api-doc-generator ............................ SUCCESS [4:28.136s]
[INFO] persistence ....................................... SUCCESS [1:00.869s]
[INFO] producer-services ................................. SUCCESS [9.938s]
[INFO] consumer-services ................................. SUCCESS [10.038s]
[INFO] producer-rest-core ................................ SUCCESS [7.238s]
[INFO] consumer-rest-core ................................ SUCCESS [14.404s]
[INFO] rest-gateway ...................................... FAILURE [52.176s]
[INFO] admin ............................................. SKIPPED
[INFO] client-ui ......................................... SKIPPED
[INFO] absaoss-spline-client ............................. SKIPPED
[INFO] client-web ........................................ SKIPPED
[INFO] spark-bundle-2.2 .................................. SKIPPED
[INFO] spark-bundle-2.3 .................................. SKIPPED
[INFO] spark-bundle-2.4 .................................. SKIPPED
[INFO] examples .......................................... SKIPPED
[INFO] integration-tests ................................. SKIPPED
[INFO] spline ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42:54.182s
[INFO] Finished at: Tue Nov 12 19:31:00 IST 2019
[INFO] Final Memory: 58M/731M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project rest-gateway: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "npm" (in directory "/root/spline-develop/rest-gateway"): error=2, No such file or directory
[ERROR] around Ant part ...<exec failonerror="true" executable="npm" osfamily="unix">... @ 8:61 in /root/spline-develop/rest-gateway/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rest-gateway

**Comment by wajda** [comment]
> Cannot run program "npm" (in directory "/root/spline-develop/rest-gateway"): error=2, No such file or directory
It cannot find `npm` command. Seems like the this point is missing from the documentation.
Please install nodeJS and try again.

**Comment by kaustubhghode** [comment]
Thanks Alex,
after installing npm ,and re running it ,I am getting the following error.
[INFO] Executing tasks

main:
     [echo] installing redoc-cli
     [exec] /root/spline-develop/rest-gateway
     [exec] └── redoc-cli@0.9.2
     [exec]
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec] npm WARN enoent ENOENT: no such file or directory, open '/root/spline-develop/rest-gateway/package.json'
     [exec] npm WARN react-hot-loader@4.12.17 requires a peer of @types/react@^15.0.0 || ^16.0.0 but none was installed.
     [exec] npm WARN rest-gateway No description
     [exec] npm WARN rest-gateway No repository field.
     [exec] npm WARN rest-gateway No README data
     [exec] npm WARN rest-gateway No license field.
     [echo] generate consumer documentation
     [exec] /root/spline-develop/rest-gateway/node_modules/chokidar/index.js:151
     [exec]   async remove(item) {
     [exec]         ^^^^^^
     [exec]
     [exec] SyntaxError: Unexpected identifier
     [exec]     at createScript (vm.js:56:10)
     [exec]     at Object.runInThisContext (vm.js:97:10)
     [exec]     at Module._compile (module.js:549:28)
     [exec]     at Object.Module._extensions..js (module.js:586:10)
     [exec]     at Module.load (module.js:494:32)
     [exec]     at tryModuleLoad (module.js:453:12)
     [exec]     at Function.Module._load (module.js:445:3)
     [exec]     at Module.require (module.js:504:17)
     [exec]     at require (internal/module.js:20:19)
     [exec]     at Object.<anonymous> (/root/spline-develop/rest-gateway/node_modules/redoc-cli/index.js:23:20)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.506s
[INFO] Finished at: Wed Nov 13 12:04:32 IST 2019
[INFO] Final Memory: 47M/843M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project rest-gateway: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec failonerror="true" executable="node_modules/.bin/redoc-cli" osfamily="unix">... @ 15:85 in /root/spline-develop/rest-gateway/target/antrun/build-main.xml.


IT has something to do with redoc-cli ,i think through npm it is not able to download redoc-cli.

**Comment by wajda** [comment]
That's strange. What NodeJS / npm version are you using?
Here's a build log from our CI environment, for example.
https://teamcity.jetbrains.com/viewLog.html?buildTypeId=OpenSourceProjects_AbsaOSSSpline_AutomaticBuildsWithTests_Spark24&buildId=2630057&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=5959
 
Could you please compare it with yours? Perhaps it will shed some light.

**Comment by wajda** [comment]
I assume it's solved in Spline 0.4.0 release.
Closing the issue. Please feel free to re-open it if the problem persists.
