### ISSUE TITLE
"2.2.x" Error when using spark 2.3

### ISSUE THREAD

**Issue by tooptoop4** [AbsaOSS/spline#46]
When trying spline with Spark 2.3.1 got an error about 2.2.x is required. Seems this code below says 2.2

https://github.com/AbsaOSS/spline/blob/master/core/src/main/scala/za/co/absa/spline/core/SparkVersionInfo.scala 

However, https://github.com/AbsaOSS/spline/releases seems to mention "[SL-116] - Fix Spark 2.3 compatibility" fix was included in spline 0.3.1 release

**Comment by vackosar** [comment]
That class is unfortunate leftover dead code. Can you share your POM used to build your project and full exception trace? As in spline-sample project you need to have correct spark version adapter. Profiles are used for that in Spline build.
```
        <dependency>
            <groupId>za.co.absa.spline</groupId>
            <artifactId>spline-core-spark-adapter-spark-2.3</artifactId>
            <version>${project.version}</version>
        </dependency>
```

**Comment by wajda** [comment]
Yep, the `SparkVersionInfo` class is unused and was just forgotten to be removed. It is very strange that it popped up in your stack trace.... Are you sure that you are using Spline 0.3.1?
As Vaclav correctly pointed in Spline 0.3 you need to include two dependencies into your POM: Spline core and a Spark adapter corresponding to the Spark version in use.
