### ISSUE TITLE
Integrate spline with pyspark 

### ISSUE THREAD

**Issue by maorshechter** [AbsaOSS/spline#48]
We work with pyspark to run our processes , is it possible to use spline ?  Which changes are needed? It will be really helpfull if you add example / snippets

**Comment by wajda** [comment]
We never think about it, but sounds like a good idea. I'll work on it.

**Comment by wajda** [comment]
https://stackoverflow.com/questions/44082957/how-to-add-a-sparklistener-from-pyspark-in-python

**Comment by maorshechter** [comment]
Thanks thread on stackover flow looks very complicated , is it the simplest
way?

**Comment by vackosar** [comment]
Have u been able to resolve this. I recon the solution wud be also akin to Java use:
https://github.com/AbsaOSS/spline/issues/43#issuecomment-398665082

**Comment by brunoRenzo6** [comment]
@vackosar @wajda SPLINE is a greate tool, we've been using it in our company inside jobs but just like @maorshechter we work with pyspark to run our process, therefore we came up with a solution for SPLINE and PYSPARK Integration. 
The solution is : write a PysparkHandler object in Scala to receive the SparkSession from PySpark, and return a SparkSession with SPLINE enabled.
Pretty Simple Implementation, take a look : https://github.com/WilliamPorto/keyruslab-spline/blob/master/Integra%C3%A7%C3%A3o.md

**Comment by wajda** [comment]
@brunoRenzo6 Wow, that's awesome! Thank you for contribution! I'll add it to the Spline docs.

**Comment by vackosar** [comment]
@brunoRenzo6 thanks for the tips. I modified the our API and here is example how you can run Spline via PySpark: https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py

It should be released soon.

**Comment by rakekris** [comment]
> @vackosar @wajda SPLINE is a greate tool, we've been using it in our company inside jobs but just like @maorshechter we work with pyspark to run our process, therefore we came up with a solution for SPLINE and PYSPARK Integration.
> The solution is : write a PysparkHandler object in Scala to receive the SparkSession from PySpark, and return a SparkSession with SPLINE enabled.
> Pretty Simple Implementation, take a look : https://github.com/WilliamPorto/keyruslab-spline/blob/master/Integra%C3%A7%C3%A3o.md

Hi Team

We are using Livy to run our pyspark jobs , any insights on how to enable spline with Livy?

**Comment by rakekris** [comment]
> @brunoRenzo6 thanks for the tips. I modified the our API and here is example how you can run Spline via PySpark: https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py
> 
> It should be released soon as part of 0.3

Hi Team

We are using Livy to run our pyspark jobs , any insights on how to enable spline with Livy?

code snippet 
data = {
	'file': self.file,
	'name': self.name,
	'args': self._encode_spark_args(self.spark_args, context),
	'conf': self.conf
}
url = self.livy_url or "http://{}:8998/".format(emr_master_ip)
r = requests.post(url + "batches", json=data)
req = r.request
