### ISSUE TITLE
Run Spline with Spark 2.1.x 

### ISSUE THREAD

**Issue by zackmeso** [AbsaOSS/spline#49]
Hello, 

I'm wondering if there's a way for Spline to be compatible with Spark 2.1.x. Because given the context i'm working in, it'll be hard to migrate to Spark 2.2.x (and higher). And a lineage tool like Spline is of a must for us. 

Are there any workarounds? If so, please share with us.

**Comment by vackosar** [comment]
You can attempt implementing custom adapter like core-spark-adapter-2.2. I am not sure how hard that would be. It could be potentially easy. If you do, please share it here via a pull request.

**Comment by vackosar** [comment]
Good luck

**Comment by mn-mikke** [comment]
Just a quick comment on writting an adapter for 2.1.x. I think you will hit a general problem with listeners of ```ExecutionListenerManager``` in 2.1.x. They don't receive any event when you try to persist results to files of any format.

Personally, I don't think there is any straightforward solution for 2.1.x. In theory, you could duplicate logic in ```SplineQueryExecutionListener``` and call ```onSuccess``` with ```yourDataframe.queryExecution before you call an action. Unfortunately, this lineage will miss information about the action and also a path of persisted results. As a consequence of this, it won't be possible to link several jobs together.
