### ISSUE TITLE
Corrupted Operation Details View

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#491]
https://opensource.bigusdatus.com/spline/ui/app/lineage-detailed/4f640f91-507b-4fab-8655-18960305d790?selectedNode=4f640f91-507b-4fab-8655-18960305d790:2

![image](https://user-images.githubusercontent.com/795479/69887292-84eb1b80-12e6-11ea-9493-6e27358befb6.png)

**Comment by wajda** [comment]
![image](https://user-images.githubusercontent.com/795479/69887443-3b4f0080-12e7-11ea-8df4-b9ad9ddd1aef.png)

**Comment by wajda** [comment]
The strange `#337AB7` label appears on all environments including localhost and `ng serve`
Missing expressions are only reproducible when running WAR (also on localhost), while using `ng serve` they are on place.

**Comment by leborgneromain** [comment]
This is is the current branch that I've created : missing-properties. It is not in develop. Although I will fix it in this PR : https://github.com/AbsaOSS/spline/pull/489
