### ISSUE TITLE
S3 object/path should be aws_s3_object type in Atlas not hdfs_path

### ISSUE THREAD

**Issue by tooptoop4** [AbsaOSS/spline#50]
Atlas 1.1 released recently added this feature for S3 type.
https://issues.apache.org/jira/browse/ATLAS-2760

Ideally spline will recognize s3a path as this type not as a hdfs_path. Then import object tags from s3

**Comment by wajda** [comment]
We won't support Atlas anymore. In the future Atlas integration can be re-introduced in Spline 0.4 as a 3rd party plugin using Spline API
