### ISSUE TITLE
Dependencies are not found

### ISSUE THREAD

**Issue by MrBigtool** [AbsaOSS/spline#509]
For this dependencies:

  "za.co.absa.spline" % "admin" % "0.4.0",
  "za.co.absa.spline" % "rest-gateway" % "0.4.0",
  "za.co.absa.spline" % "client-web" % "0.4.0"

SBT shows:

[warn] 	**module not found: com.github.wajda.com.arangodb#velocypack1.4-module-scala_2.11;1.0.3.4**
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/wajda/com/arangodb/velocypack1.4-module-scala_2.11/1.0.3.4/velocypack1.4-module-scala_2.11-1.0.3.4.pom

It seems https://repo1.maven.org/maven2/com/github/wajda/ has not contain folder "com"

**Comment by wajda** [comment]
This particular dependency is hosted on GitHub - https://raw.githubusercontent.com/wajda/java-velocypack-module-scala/mvn-repo/com/github/wajda/com/arangodb/velocypack1.4-module-scala_2.11/1.0.3.4/velocypack1.4-module-scala_2.11-1.0.3.4.pom
This is a temporary one, we'll either get rid of it in the next version or will make it a proper Maven hosted.

See this part of the [`parent/pom.xml`](https://github.com/AbsaOSS/spline/blob/release/0.4.0/parent/pom.xml#L753):
```xml
<repositories>
        <repository>
            <id>java-velocypack-module-scala-mvn-repo</id>
            <url>https://raw.githubusercontent.com/wajda/java-velocypack-module-scala/mvn-repo/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

I didn't try SBT, but when using Maven it's resolved with no issues. Try to add this repository to your SBT project directly.

Also, I don't know if you noticed, and not sure if that will be an issue in your case, but some people in past reported issues about using Spline in SBT based project - #160
We still has yet to address it.

**Comment by MrBigtool** [comment]
Thanks! it is resolved
