### ISSUE TITLE
REQUIRED mode is not working

### ISSUE THREAD

**Issue by MrBigtool** [AbsaOSS/spline#517]
REQUIRED mode (in master branch) shows following error (spline/examples/src/main/scala/za/co/absa/spline/example/batch/Example3Job.scala):

> Exception in thread "main" scala.MatchError: Success(true) (of class scala.util.Success)
> 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.ensureProducerReady(HttpLineageDispatcher.scala:69)
> 	at za.co.absa.spline.harvester.SparkLineageInitializer$SparkSessionWrapper.enableLineageTracking(SparkLineageInitializer.scala:80)
> 	at za.co.absa.spline.example.batch.Example3Job$.delayedEndpoint$za$co$absa$spline$example$batch$Example3Job$1(Example3Job.scala:25)
> 	at za.co.absa.spline.example.batch.Example3Job$delayedInit$body.apply(Example3Job.scala:24)
> 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
> 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> 	at scala.App$$anonfun$main$1.apply(App.scala:76)
> 	at scala.App$$anonfun$main$1.apply(App.scala:76)
> 	at scala.collection.immutable.List.foreach(List.scala:392)
> 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
> 	at scala.App$class.main(App.scala:76)
> 	at za.co.absa.spline.example.SparkApp.main(SparkApp.scala:27)
> 	at za.co.absa.spline.example.batch.Example3Job.main(Example3Job.scala)

It seems this mode tries to connect to producer but my producer is ok, in fact BEST_EFFORT mode works perfectly.

**Comment by cerveada** [comment]
Yes this is a bug, thanks for reporting. Please use BEST_EFFORT mode until this is fixed.

**Comment by wajda** [comment]
duplicate for #515
