### ISSUE TITLE
WebJar isn't published to Maven automatically

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#518]
See: https://www.webjars.org/contributing

**Comment by wajda** [comment]
@benedeki

**Comment by wajda** [comment]
The problem is that according to _WebJar_'s contribution rules _groupId_ is required to be exactly `org.webjars`. so the artifact cannot be published to Maven central together with the other Spline modules in the scope of the same deployment cycle.
To do it properly we'd need to follow _WebJar_'s contribution process, creating a separate repo, request them to fork/build/publish etc. But since we don't have any reason to list our webjar among the rest of public webjars it apparently means that there is nothing that stops us from switching to Spline's _groupId_ to make our lives easier. By doing it we could even get rid of the webjar dedicated pom in our project and simply produce `client-ui.jar` as another `client-ui` module artifact.
So we're gonna break _WebJar_'s convention a little for the sake of simplicity and maintainability.

**Comment by benedeki** [comment]
How can I use that jar (I guess the `client_ui.jar` from now) in my controler then?

**Comment by wajda** [comment]
Yes, there's no dedicated spline-webjar dependency anymore, please use `client-ui.jar` instead. It's technically a webjar, but just doesn't manifest itself like such in the POM.

**Comment by wajda** [comment]
the path to the `index.html` inside the jar has also changed from `/webjars/absaoss-spline-client/` to just `/webjars/spline/`
