### ISSUE TITLE
Codeless Spline Initialization in Spark

### ISSUE THREAD

**Issue by shubhluck** [AbsaOSS/spline#536]
Need to run spark job with already setup spline 0.4 in yarn cluster mode, below properties need to be included in spark submit script:

- spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener
- -Dspline.producer.url=[producer_url]

## Question
Where and how to set spline producer url in the script and earlier in 0.3 we were including spline bundle jar in the script, but now which jar need to be send to worker nodes ?

**Comment by wajda** [comment]
Hi,
From the perspective of the Spline agent (aka harvester) configuration and activation it's pretty similar to how it was done in Spline 0.3. There are agent-bundles prebuilt for three major Spark versions (2.2-2.4) that need to be included into the Spark driver class path (nothing is sent to workers, only driver). You could simply copy the respective bundle.jar to the `$SPARK_HOME/jars` dir if you have an access, or send  it as a part of you `pyspark` or `spark-submit` command via `--jars` parameter. You could also use `--packages` but there apparently a bug in the Spark script or a packaging issue in Spline that prevent the script to resolve the jar properly. `--jars` works fine though.

Producer URL is what it says to be - the URL to the Spline Producer API, which depends on how you run the Spline server. If you run Spline REST Gateway, then it's you gateway root URL + `/producer`

**Comment by shubhluck** [comment]
Thanks @wajda  for the answer, but which spark property to use to set __-Dspline.producer.url=http://localhost:8080/producer_ ?

**Comment by wajda** [comment]
Try `--conf "spark.spline.producer.url=http://localhost:8080/producer`
