### ISSUE TITLE
Detailed lineage graph not showing up

### ISSUE THREAD

**Issue by iamgzy** [AbsaOSS/spline#537]
## Background [Optional]
Spline 0.3.9
Performed a Spline testing on current process, however when clicked on Detailed lineage graph (gear button) nothing showed up

## Question
We just try to figure out if the issue comes within our code or Spline

1. There are some exceptions (yes, several similar exception but pretty much the same cause) while running our Spark code
>ERROR CodeGenerator: failed to compile: org.codehaus.commons.compiler.CompileException: File 'generated.java', Line 567, Column 28: Redefinition of parameter "agg_expr_21"                      
org.codehaus.commons.compiler.CompileException: File 'generated.java', Line 567, Column 28: Redefinition of parameter "agg_expr_21"

These errors should be pretty benign as our final results generated correctly, but not sure how it impacts Spline's result

2. We have some code on rdd but it is for the dataframe so I don't think they are RDD api and should pick up by Spline

>val tableDf= spark.sql("blah....")
>val releaseDate= tableDf.where(tableDf("item") <=> "releaseDate").select("value").rdd.map(_.getString(0)).toLocalIterator.toList.head

3. Where to find Spline log to track any exception or error from Spline?

Thanks in advance for any advice.

**Comment by wajda** [comment]
Hi @iamgzy 
It looks like the whole-stage generation failed for your Spark job. I cannot tell why the job still worked, perhaps it fell back to a Volcano iteration, but not quite sure.
In theory it could affect Spline in a way that it produced a strange execution plan that couldn't be rendered correctly. It would be helpful to see the browser errors (if any) and the response from the REST calls.

Regarding RDD, those aren't supposed by Spline. If you use ones then Spline will only capture the part of the lineage from the write operetion up until an RDD operation. The part of the chain preceeding an RDD operation will be lost.

**Comment by iamgzy** [comment]
Thanks will try to capture restful log from browser

Do you mean the rdd syntax example above won’t be capture in the down
stream process? Meaning any lineage after the val object from rdd is no
longer traced by spline, I guess we can rewrite the part for spline
integration. However this issue should not cause the missing of detail
graph?

**Comment by wajda** [comment]
No, it's více versa - the transformations before `.rdd` call will not be traced. A lineage is always traced from a write-operation back to the sources. RDD however, been a low level API, don't retain any logical plan and hence will appear as a terminal node on the lineage graph.
Anither problem occurs when you call a non-write action on your DaraFrane or RDD - you trigger the computation and get the actual result in memory. But since any actual write hasn't been performed Spline has no chance to track how you use that data after that. Thus the lineage is ignored.
You really have to stick with `DataFrame` API through your entire pipeline to capture the lineage. And it is also the most efficient way to use Spark anyway.

**Comment by iamgzy** [comment]
Thanks @wajda 

For that's worth here is the javascript error from developer console

vis.js:51157 Node does not exist.
core.js:15724 ERROR TypeError: Cannot read property '_typeHint' of null
    at o (types.ts:65)
    at Object.t.typeOfExpr (types.ts:57)
    at e.renderValue (expression-render.service.ts:111)
    at expression-render.service.ts:114
    at Array.map (<anonymous>)
    at e.renderValue (expression-render.service.ts:114)
    at expression-render.service.ts:104
    at lodash.js:3549
    at lodash.js:4911
    at Pn (lodash.js:2996)

**Comment by wajda** [comment]
Seems to be similar to #218 
Can you attach the full REST response? And the Spark script please.

Also have you tried this in Spline 0.4?

**Comment by iamgzy** [comment]
> Seems to be similar to #218
> Can you attach the full REST response? And the Spark script please.
> 
> Also have you tried this in Spline 0.4?

@wajda Sorry due to policy I can't expose the data from rest response and script. It's all http 200 with a lot of lineage data pulled from mongodb

I haven't tried the Spline 0.4.

Right now I am working on resolving the exception from generated.java and removing rdd. I tend to sort out the code internally first and see if it make a difference.

I will keep posted and thank you, merry Christmas to everyone from Spline team! Santa came early and sent the gift of Spline 0.4 :)
