### ISSUE TITLE
Data Impact / Forward lineage analysis

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#540]
Opposite and complimentary to the (Backward) Data Lineage.
Traces how the data is used / errors are propagated down the pipeline

**Comment by wajda** [comment]
Probably. The work on 0.6 has been suspended for the last month or so due to performance issues found in 0.5.3 that affect some production usages and had to be addressed. We'll have another round of 0.6 planning somewhere next week and clarify on this issue.

**Comment by pratapmmmec** [comment]
Thanks for confirming @wajda . Fingers crossed for this epic.

**Comment by dk1844** [comment]
The backend part of forward lineage (aka impact) on the service-side merged to `develop`. Note, that there is no UI support for this feature, yet.
