### ISSUE TITLE
Is spline4.0 support atlas integration?

### ISSUE THREAD

**Issue by bjwanghua** [AbsaOSS/spline#542]
Is spline4.0 support atlas integration? Where can I find a guid?thanks

**Comment by wajda** [comment]
Hi @bjwanghua,
No, Spline 0.4 doesn't have Atlas integration. And most likely it won't have it out of the box. See #279 
However it can easily be implemented as a 3rd party extension to the Spline Spark Agent, by extending [`LineageDispatcher`](https://github.com/AbsaOSS/spline/blob/release/0.4/spark/agent/src/main/scala/za/co/absa/spline/harvester/dispatcher/LineageDispatcher.scala) trait and registering it via `spline.lineage_dispatcher.className` agent config parameter.

**Comment by bjwanghua** [comment]
o， I've learned. I will try it out, thanks.
