### ISSUE TITLE
Run spline 0.4.0 in docker

### ISSUE THREAD

**Issue by spy86** [AbsaOSS/spline#550]
Does container-based spline 0.4.0 work correctly? I try to run them according to the documentation (https://absaoss.github.io/spline/), however the spline-web-client component has a problem connecting to consumer with URL :http://172.17.0.1:8080/consumer

**Comment by Zejnilovic** [comment]
This is what I just ran locally

```
docker container run \
      -e spline.database.connectionUrl=arangodb://root@host.docker.internal/SplineOne \
      -p 8080:8080 \
      absaoss/spline-rest-server
```

```
docker container run \
      -e spline.consumer.url=http://192.168.0.24:8080/consumer \
      -p 9090:8080 \
      absaoss/spline-web-client
```

Works well. If you have a follow-up. Please do provide more information. What have you ran and how does it behave exactly.

**Comment by Zejnilovic** [comment]
Hello @spy86, may I ask you how is your spline usage going? Do you have more questions or do we close this issue?

**Comment by spy86** [comment]
Hello @Zejnilovic 

We can close this issue. Thanks
