### ISSUE TITLE
Improve spark-agent "sanity check" error messages

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#554]
The message should give more information about what is working and what not.

**Comment by wajda** [comment]
Using `getRequiredString` was a quick change but is useless due to the exception thrown from the `getString`

**Comment by wajda** [comment]
Fixed by https://github.com/AbsaOSS/commons/commit/fec10cd78a786e176c90d638235b7243dffed71e#diff-88ae8be6e2391263e2c736099db9a4fdR107
