### ISSUE TITLE
Unable to see jobs in spline UI. Spline version 0.4.1

### ISSUE THREAD

**Issue by Nikhith-kudumula** [AbsaOSS/spline#557]
Hi Team,

I have setup spline version 0.4.1 in my cluster using tomcat. I have also installed arango DB in My cluster.

I am able to access spline Web UI, and also created spline _db in arango, able to access - 
http://{host}:{port}/rest-gateway-0.4.1/consumer/execution-events - Json respone. 

my consumer URL as : http://{host}:{port}/rest-gateway-0.4.1/consumer 
my producer URL: http://{host}:{port}/rest-gateway-0.4.1/producer

## Question
I am unable see my jobs in spline UI, when i  run from spark2-shell -> spark version - 2.3.x
Spline UI - http://{HOST}:{PORT}/client-web-0.4.1/app/dashboard

spark2-shell --driver-java-options='-Dspline.mode=REQUIRED -Dspline.spline.producer.url=http://{hostname}:{port}/rest-gateway-0.4.1/producer' --jars /jars/path/spark-agent-0.4.1.jar,/jars/path/admin-0.4.1.jar

import za.co.absa.spline.harvester.SparkLineageInitializer._
spark.enableLineageTracking(_)

Assuming Issue is with wrong producer and consumer URL, 
Could you please suggest.

**Comment by cerveada** [comment]
Hello Nikhith, are you able to see your jobs in arango db client?

**Comment by Nikhith-kudumula** [comment]
Hello cerveada, am not able to see any jobs in arango db as well...

**Comment by wajda** [comment]
Please check logs. If you see the message saying that lineage tracking is enabled, and no exceptions, then it can indicate that Spline agent simply didn't capture any trackable action. Spline only captures actions that actually write data into a persistent store (like file or database).

**Comment by Nikhith-kudumula** [comment]
Hi wajda,

Can you please let me know what is the producer URL ?

**Comment by wajda** [comment]
As mentioned in the doc - https://absaoss.github.io/spline/0.4.html
The _Producer URL_ is the root URL of the _Producer_ web application.
If you are running Spline Gateway app (which includes both Consumer and Producer) on say [http://localhost:8080] then the Producer URL is [http://localhost:8080/producer]

**Comment by Nikhith-kudumula** [comment]
Hi wajda,

I have added producer-model-0.4.1.jar, which helped in resolving the issue. Now i am able to see lineage in Spline UI.
Thanks for your support.
