### ISSUE TITLE
Admin CLI doesn't exit normally

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#565]
Presumable caused by #396

**Comment by cerveada** [comment]
It seems to be caused by Arangodb driver bug.

I opend a ticket on their github: https://github.com/arangodb/arangodb-java-driver/issues/333

**Comment by cerveada** [comment]
fixed https://github.com/AbsaOSS/spline/commit/c3c5b066f7093506df521ce90e7d38bbbb456ff2
