### ISSUE TITLE
Spline 0.4.1 build issue in Windows 10

### ISSUE THREAD

**Issue by Qurashetufail** [AbsaOSS/spline#566]
Hi Team, 

I am facing the below issue while running the 
# Command 
`mvn install -DskipTests `

on spline 0.4.1v

# Error
```
main:
     [echo] installing redoc-cli
     [exec] npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
     [exec] npm WARN rest-gateway No description
     [exec] npm WARN rest-gateway No repository field.
     [exec] npm WARN rest-gateway No license field.
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
     [exec]
     [exec] + redoc-cli@0.9.5
     [exec] updated 1 package and audited 1202 packages in 9.987s
     [exec] found 0 vulnerabilities
     [exec]
     [echo] generate consumer documentation
     [exec] SyntaxError: "c:/Users/Tufail/Desktop/Project/Spline%200.4v/spline-release-0.4.1/rest-gateway/0.4v/spline-release-0.4.1/rest-gateway/target/api/docs/consumer.html" is not a valid JSON Schema
     [exec]     at C:\Users\Tufail\Desktop\Project\Spline 0.4v\spline-release-0.4.1\rest-gateway\node_modules\json-schema-ref-parser\lib\index.js:114:19
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spline 0.4.1:
[INFO]
[INFO] Spline ............................................. SUCCESS [  3.370 s]
[INFO] commons ............................................ SUCCESS [ 30.375 s]
[INFO] producer-model ..................................... SUCCESS [  6.253 s]
[INFO] spark-agent ........................................ SUCCESS [ 29.620 s]
[INFO] migrator-tool ...................................... SUCCESS [ 30.593 s]
[INFO] rest-api-doc-generator ............................. SUCCESS [ 21.346 s]
[INFO] persistence ........................................ SUCCESS [ 20.111 s]
[INFO] producer-services .................................. SUCCESS [ 12.125 s]
[INFO] consumer-services .................................. SUCCESS [  8.241 s]
[INFO] producer-rest-core ................................. SUCCESS [  7.073 s]
[INFO] consumer-rest-core ................................. SUCCESS [ 11.946 s]
[INFO] rest-gateway ....................................... FAILURE [ 27.510 s]
[INFO] admin .............................................. SKIPPED
[INFO] client-ui .......................................... SKIPPED
[INFO] client-web ......................................... SKIPPED
[INFO] spark-agent-bundle-2.2 ............................. SKIPPED
[INFO] spark-agent-bundle-2.3 ............................. SKIPPED
[INFO] spark-agent-bundle-2.4 ............................. SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] integration-tests .................................. SKIPPED
[INFO] spline ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:28 min
[INFO] Finished at: 2020-01-24T15:19:10+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project rest-gateway: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec failonerror="true" executable="cmd" osfamily="windows">... @ 12:64 in C:\Users\Tufail\Desktop\Project\Spline 0.4v\spline-release-0.4.1\rest-gateway\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rest-gateway
```
there is no consumer.html file present at the said path. After i created the html file myself, the error still presists.

Thanks,
Tufail

**Comment by wajda** [comment]
`Project\Spline 0.4v\`
Try without a space in the path.

**Comment by Qurashetufail** [comment]
Thanks for the help, This issue is resolved but a new issue is occuring

main:
     [exec] "Building Spline UI v0.4.1"
     [exec]
     [exec] > core-js@3.1.4 postinstall C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\node_modules\@angular-devkit\build-angular\node_modules\core-js
     [exec] > node scripts/postinstall || echo "ignore"
     [exec]
     [exec] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
     [exec]
     [exec] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
     [exec] > https://opencollective.com/core-js
     [exec] > https://www.patreon.com/zloirock
     [exec]
     [exec] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
     [exec]
     [exec]
     [exec] > core-js@3.2.1 postinstall C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\node_modules\global-agent\node_modules\core-js
     [exec] > node scripts/postinstall || echo "ignore"
     [exec]
     [exec] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
     [exec]
     [exec] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
     [exec] > https://opencollective.com/core-js
     [exec] > https://www.patreon.com/zloirock
     [exec]
     [exec] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
     [exec]
     [exec]
     [exec] > @angular/cli@8.2.0 postinstall C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\node_modules\@angular\cli
     [exec] > node ./bin/postinstall/script.js
     [exec]
     [exec] added 1200 packages from 1082 contributors and audited 19304 packages in 70.587s
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
     [exec]
     [exec] found 18 vulnerabilities (1 low, 4 moderate, 13 high)
     [exec]   run `npm audit fix` to fix them, or `npm audit` for details
     [echo] Build Spline Webjar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spline 0.4.1:
[INFO]
[INFO] Spline ............................................. SUCCESS [  6.255 s]
[INFO] commons ............................................ SUCCESS [ 43.226 s]
[INFO] producer-model ..................................... SUCCESS [  6.757 s]
[INFO] spark-agent ........................................ SUCCESS [ 35.743 s]
[INFO] migrator-tool ...................................... SUCCESS [ 37.528 s]
[INFO] rest-api-doc-generator ............................. SUCCESS [ 23.764 s]
[INFO] persistence ........................................ SUCCESS [ 23.394 s]
[INFO] producer-services .................................. SUCCESS [ 13.969 s]
[INFO] consumer-services .................................. SUCCESS [  9.906 s]
[INFO] producer-rest-core ................................. SUCCESS [  6.464 s]
[INFO] consumer-rest-core ................................. SUCCESS [ 14.394 s]
[INFO] rest-gateway ....................................... SUCCESS [01:10 min]
[INFO] admin .............................................. SUCCESS [ 24.491 s]
[INFO] client-ui .......................................... FAILURE [01:18 min]
[INFO] client-web ......................................... SKIPPED
[INFO] spark-agent-bundle-2.2 ............................. SKIPPED
[INFO] spark-agent-bundle-2.3 ............................. SKIPPED
[INFO] spark-agent-bundle-2.4 ............................. SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] integration-tests .................................. SKIPPED
[INFO] spline ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:35 min
[INFO] Finished at: 2020-01-24T16:21:01+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project client-ui: An Ant BuildException has occured: C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\dist\ui2 does not exist.
[ERROR] around Ant part ...<copy todir="C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\target\classes/META-INF/resources/webjars/spline/0.4.1">... @ 13:149 in C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :client-ui

**Comment by wajda** [comment]
what Node/NPM version are you using?

A side note - all Spline artifacts are available in Maven central and Docker Hub. So unless you want to play with Spline source code you don't have to build it yourself.

**Comment by Qurashetufail** [comment]
Thankyou for the help. 

Node version is v12.14.1
NPM version is 6.13.4

For future reference, please let me know which version is compatible with spline 0.4.1.

**Comment by wajda** [comment]
that should be perfectly fine.

```
C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\spline-release-0.4.1\client-ui\dist\ui2 does not exist.
```
I don't know why it happens, but it looks like the angular build didn't finish (was killed, failed or somehow just didn't produce any output).
Try `mvn clean install -DskipTests` one more time. If it doesn't help, try to run the UI build manually:
```shell
cd client-ui
build.cmd
```
and then check if `dist/ui2` exists.
If so, try to run the Maven build one more time.

**Comment by Qurashetufail** [comment]
Hi @wajda 

I tried the above process but still failed. When i tried to build the UI manually i got the following message
C:\Users\Tufail\Desktop\Project\Spline_v0.4.1\0.4.1\spline-release-0.4.1\client-ui>build.cmd
"Building Spline UI v"
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN cytoscape-ng-lib@2.0.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN cytoscape-ng-lib@2.0.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-bootstrap-switch@0.0.3 requires a peer of @angular/core@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.

audited 19079 packages in 6.406s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Is it something i have to install manually or do I have to install angularjs for this? If yes, please let me know which version of AngularJS I have to install.

Thanks,
Tufail

**Comment by wajda** [comment]
Unfortunately I cannot reproduce it. I've seen somebody on github mentioned a similar problem before, but we couldn't reproduce it. For us Spline is build with no issues on Linux, Mac and Windows 10
