### ISSUE TITLE
Spline Compatibility

### ISSUE THREAD

**Issue by Qurashetufail** [AbsaOSS/spline#567]
Hi Team,

I have the following question regarding the compatibility of Spline and further versions of the spline.

1. Is the Spline 0.3.9 version still supported?
1. Does Spline 0.4.0 support MongoDB, HDFS and Databricks cluster other than ArangoDB?
2. Do you still support Spline 0.3.9v with the Databricks cluster?

Thanks,
Tufail

**Comment by wajda** [comment]
Hi @Qurashetufail,

Long answer is here - https://absaoss.github.io/spline/2019/12/16/Spline-0.4-has-arrived.html

Short answer is:
1. No, Spline 0.3 is not longer maintained.
2. No, Spline 0.4 only works with ArangoDB.

But dumping lineage on HDFS in a way how Spline 0.3 did it is extremely simple task. For this you don't even need the whole Spline. All you need is Spline Spark Agent - the module that captures the Spark  lineage and send it as a JSON to Spline Producer.
You can easily create your own implementation of [LineageDispatcher](https://github.com/AbsaOSS/spline/blob/release/0.4.1/spark/agent/src/main/scala/za/co/absa/spline/harvester/dispatcher/LineageDispatcher.scala) trait and save the lineage to HDFS. The implementation of the _save_ itself is just a few lines of code - see [HdfsDataLineageWriter.scala](https://github.com/AbsaOSS/spline/blob/release/0.3.9/persistence/hdfs/src/main/scala/za/co/absa/spline/persistence/hdfs/HdfsDataLineageWriter.scala) for reference.
Then you just need to register your `HDFSLineageDispatcher` class via `spline.lineage_dispatcher.className` conf property. See #463 and #468

**Comment by Qurashetufail** [comment]
Hi @wajda 

Thank you for answers.

Thanks,
Tufail
