### ISSUE TITLE
Invalid docker-compose.yml URL mentioned on the documentation

### ISSUE THREAD

**Issue by arunravilla** [AbsaOSS/spline#568]
Getting 404 for the docker-compose file URL mentioned in README.MD
https://raw.githubusercontent.com/AbsaOSS/spline/master/docker-compose.yml

**Comment by wajda** [comment]
Sorry for the confusion, but the doc is intended for the future release (you are looking at the `develop` branch). If you want to try the snapshot version, you'll need to clone the repo and build it yourself.
