### ISSUE TITLE
Links in the project's main page lead to 404 

### ISSUE THREAD

**Issue by mrjoseph84** [AbsaOSS/spline#574]
## Describe the bug
The links in the project main page (e.g. Examples, ClientUI, etc.) give 404. Please kindly fix them. Thx!

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Go to: https://absaoss.github.io/spline/examples/README.md
2. See error: 404

## Desktop (please complete the following information):
- OS: [iOS]
- Browser [Chrome]

**Comment by wajda** [comment]
Thanks, will fix it.
Meantime you can the example info here - https://github.com/AbsaOSS/spline/tree/release/0.4.1/examples

**Comment by cerveada** [comment]
Documentation was moved to [Spline GitHub Pages](https://absaoss.github.io/spline/). Links there should work fine.
