### ISSUE TITLE
Azure does not allow environment variables with '.' separator

### ISSUE THREAD

**Issue by MrBigtool** [AbsaOSS/spline#579]
We are deploying "absaoss/spline-rest-server" docker image into Azure Container Instances (ACI) and that service does not allow an environment variable 'spline.database.connectionUrl' because they expect a '_' separator, exactly this will be correctly for them: 'spline_database_connectionUrl'. Could you change your code for allowing both options?

<img width="1122" alt="Captura de pantalla 2020-02-06 a las 12 16 02" src="https://user-images.githubusercontent.com/8641619/73932499-c39ae480-48da-11ea-9364-8278f3862927.png">

**Comment by MrBigtool** [comment]
If you are agree with this change I can try do a pull request with this feature.

**Comment by Zejnilovic** [comment]
Hello @MrBigtool, Azure limitations are quite unfortunate but you could try doing key `JAVA_OPTS` and value `spline.database.connectionUrl=XXX`

**Comment by MrBigtool** [comment]
Exactly, thank you very much, it is solved.

**Comment by rvvincelli** [comment]
Very good point - thanks!!
