### ISSUE TITLE
Unauthorized to create database in Arango

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#586]
Following the installation instructions, it says to create a database in Arango using the command java -jar admin/target/admin-0.4.1.jar db-init arangodb://localhost/spline

Doing that leads to  Response: 401, Error: 401 - unauthorized

I have set in Arango a simple password for root, but can't seem to find anywhere in Spline to inform that pasword or to specify a username

**Comment by Zejnilovic** [comment]
When you check the help of spline's admin jar. Under the `--help` 
```
java -jar admin-<VERSION>.jar --help
```
you should find a `<db_url>` which shows: `arangodb://[user[:password]@]host[:port]/database` so basically `arangodb://myUser:myPassword@localhost:8529/spline`

**Comment by Sequential-circuits** [comment]
Thanks: I just disabled authentication at Arango

**Comment by Sequential-circuits** [comment]
At https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py it says how to run it under pyspark, but when we clone the repo the sample section does not come

**Comment by wajda** [comment]
Hi @Sequential-circuits
Please pay attention on the Spline versions you refer to. Versions 0.3 and 0.4 aren't compatible. As you are talking about ArangoDB it implies that you are using Spline 0.4.

**Comment by Sequential-circuits** [comment]
Thanks for the heads up. In such case, how do I download the sample to run python under 0.4? The repo does not seem to have it

**Comment by wajda** [comment]
https://github.com/AbsaOSS/spline/blob/release/0.4.1/examples/src/main/python/python_example.py

**Comment by wajda** [comment]
Also, due to #535.call `pyspark --jars` instead of `--packages`.
This issue has been fixed in Spline 0.5 that is not released yet.

**Comment by Sequential-circuits** [comment]
I truly appreciate your quick help. 

Still, the page you sent me to says the same I had before: "To run Spline example, download the Spline source code from GitHub and switch to the examples directory.". 

There is no examples directory in the repo at https://github.com/AbsaOSS/spline

**Comment by Sequential-circuits** [comment]
Also, the text "The different examples are located here: batch batchWithDependencies" at https://github.com/AbsaOSS/spline/tree/release/0.4.1/examples leads to 2 pages not found

**Comment by Zejnilovic** [comment]
Hello @Sequential-circuits , please note if you pulled `0.5.0-SNAPSHOT` (latest `develop` branch) or `0.4.1` release found by the tag with the same name, also found at https://github.com/AbsaOSS/spline/tree/release/0.4.1

**Comment by Sequential-circuits** [comment]
Hi: I can find /client-ui/target/classes/META-INF/resources/webjars/spline/0.5.0-SNAPSHOT in my repo

**Comment by Sequential-circuits** [comment]
Downloaded version 4.1 and please note it has a bug which version 5 does not have, namely, it does not build "failed: java.io.IOException: Cannot run program "node_modules/.bin/redoc-cli" 

The solution I found was to put that module (which I do have installed) manually at the folder it says

Hope to be useful

**Comment by Sequential-circuits** [comment]
I am trying the example mentioned at https://github.com/AbsaOSS/spline/blob/release/0.4.1/examples/src/main/python/python_example.py ("pyspark --jars target/spline-examples-0.4.0.jar...") but I get org.json4s#json4s-ext_2.11;${json4s.version}: not found

**Comment by Zejnilovic** [comment]
The error seems weird. Why isn't it saying wich version precisely it did not find?
Is there more to the error or the way you built it?

**Comment by wajda** [comment]
https://github.com/AbsaOSS/spline/issues/586#issuecomment-585846791

**Comment by Sequential-circuits** [comment]
Ok, I used the command as instructed (using --jars instead of --package) and now I get 
Exception in thread "main" java.io.IOException: No FileSystem for scheme: za.co.absa.spline

However, I do have hadoop running (namenode included) and HADOOP_HOME set

**Comment by wajda** [comment]
Can you show us the exact command that you are using?

**Comment by Sequential-circuits** [comment]
pyspark --jars /root/spline/examples/target/examples-0.4.1.jar --jars za.co.absa.spline:spark-agent-bundle-2.4:0.4.1 --conf spline.producer.url=http://localhost:8888/producer

**Comment by Sequential-circuits** [comment]
I believe its because I don't seem to have the server running. However, when trying to run it with the command  java -jar rest-gateway-0.4.1.war -Dspline.database.connectionUrl=arangodb://localhost/spline (I would suppose this is the way to run it), I get  no main manifest attribute, in rest-gateway-0.4.1.war

**Comment by wajda** [comment]
@Sequential-circuits this is your command:
```
pyspark \
    --jars PATH_TO_THE_SPLINE_SPARK_AGENT_BUNDLE_JAR_FILE \
    --conf spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener \
    --conf spark.spline.producer.url=http://localhost:8080/producer
```

`spline-spark-agent-bundle.jar` can be downloaded from Maven Central according to the Spark version you are using.
E.g. for Spark 2.4 get this jar https://repo1.maven.org/maven2/za/co/absa/spline/spark-agent-bundle-2.4/0.4.1/spark-agent-bundle-2.4-0.4.1.jar

See the updated docs - https://absaoss.github.io/spline/0.4.html#download-prebuild-spline-artifacts-from-the-maven-repo

**Comment by wajda** [comment]
Since the original question seems to be resolved, I'm closing this issue to prevent too much off topic discussion.
Please open new issues if you have more questions.
