### ISSUE TITLE
Executable war

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#592]
At https://absaoss.github.io/spline/ it says that the server can be fired from a "Java compatible Web-Container (e.g. Tomcat)". However, the webserver we run is NGINX, which will not run these (at least without some external modules etc)

And trying just to run the war with a command java -jar will yield "no main manifest attribute, in rest-gateway-0.4.1.war"

Making the war executable would be nice, especially if all is required is a manifest file. Other than that, how to run the server then if you don't have a tomcat server?

**Comment by Zejnilovic** [comment]
Hello @Sequential-circuits, you could try our docker solution. Do you have Docker available?

**Comment by Sequential-circuits** [comment]
Yes I do and that's what I am now using thanks. You may want also put in the instructions that the wars cannot be executed that way. Either way, hope my suggestion was useful :)

**Comment by cerveada** [comment]
`.war` files are by definition runnable only in servlet or application container. We could package the app and tomcat inside a jar file, but I don't really see a reason to have third way how to deploy the application. Both war files and docker containers are already pretty standard.
