### ISSUE TITLE
Docker not connecting to arangodb even though the port is right and it is configured to accept connections

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#593]
When running the command docker container run -e spline.database.connectionUrl=arangodb://127.0.0.1:8529/spline absaoss/spline-rest-server I am getting 
18:17:44.505 [main] WARN  c.a.i.velocystream.VstCommunication - Could not connect to host[addr=127.0.0.1,port=8529] or SSL Handshake failed. Try connecting to host[addr=127.0.0.1,port=8529]

Makes no sense, since I am using port 8529. Arangodb is indeed running at that port :
(lsof -i :8529
COMMAND   PID     USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
arangod 17139 arangodb   14u  IPv4 10992533      0t0  TCP localhost:8529 (LISTEN))

Also, arangodb is configured to allow connection without passwords and stuff

**Comment by Zejnilovic** [comment]
Hello @Sequential-circuits, I believe docker sees `127.0.0.1` as it's container localhost. Try `172.17.0.1`

**Comment by Sequential-circuits** [comment]
I did: same result :(

**Comment by Zejnilovic** [comment]
In regards to ArangoDB. Is your Arango running? Where is it? Is it on the same machine as Docker? Does it have security on, like username and password?

In regards to running docker with addresses, I personally use this:
```
docker container run \
      -e spline.consumer.url=http://`ipconfig getifaddr en0`:8081/consumer \
      -p 9090:8080 \
      absaoss/spline-web-client
```

The important thing is ``` `ipconfig getifaddr en0` ``` where `en0` is my network device.

**Comment by Zejnilovic** [comment]
I posted web-client by mistake, but it shouldn't matter.

**Comment by Sequential-circuits** [comment]
That is interesting. Why it shouldn't matter? Is that the ui server and the regular server are the same?

**Comment by Zejnilovic** [comment]
> That is interesting. Why it shouldn't matter? Is that the ui server and the regular server are the same?

No I mean, the important information from it is the ``` `ipconfig getifaddr en0` ``` applied as the IP address. To apply the logic to rest server:

```
docker container run \
      -e spline.database.connectionUrl=arangodb://root@`ipconfig getifaddr en0`/SplineOne \
      -p 8081:8080 \
      absaoss/spline-rest-server
```

Again, this is my showcasing my personal way I run it. Your desired port might not be 8081, your Arango user might not be root without password, etc.

**Comment by Zejnilovic** [comment]
Hello @Sequential-circuits, did you figure this out or do you have more info?
