### ISSUE TITLE
Running on python not clear

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#594]
At https://github.com/AbsaOSS/spline/blob/release/0.4.1/examples/src/main/python/python_example.py the part where it says "# Enable Spline tracking:
sc._jvm.za.co.absa.spline.harvester\
    .SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)" is not clear

It is not clear if one is supposed to import that into a python code and, if yes, how? As it seems scala code

Any help appreciated, and hope I am being useful into making it clearer to other newbies :)

**Comment by Zejnilovic** [comment]
Check the 4th point of the comments there. It is expected to run from `pyspark` whit our jar passed to it. The pyspark then should know about the path to the package and to enable lineage tracking.

If you don't use pyspark to run it, you would need to add all the spark, spline, etc. dependencies by hand. Not advised.

**Comment by Zejnilovic** [comment]
Hello @Sequential-circuits, could we close this?

**Comment by wajda** [comment]
@Sequential-circuits did you check the updated docs?
  - https://github.com/AbsaOSS/spline/tree/release/0.4/examples#python-pyspark
  - https://github.com/AbsaOSS/spline/blob/release/0.4/examples/src/main/python/python_example.py

Is it better now?
