### ISSUE TITLE
Problem running the examples (version 0.4)

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#595]
When trying to run the examples (version 0.4) at https://github.com/AbsaOSS/spline/tree/release/0.4.1/examples I get

     [java] Exception in thread "main" org.apache.spark.sql.AnalysisException: Unable to infer schema for CSV. It must be specified manually.;
     [java]     at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:183)
     [java]     at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:183)
     [java]     at scala.Option.getOrElse(Option.scala:121)
     [java]     at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:182)
     [java]     at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:353)
     [java]     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
     [java]     at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:533)
     [java]     at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:412)
     [java]     at za.co.absa.spline.example.batch.CodelessInitExampleJob$.delayedEndpoint$za$co$absa$spline$example$batch$CodelessInitExampleJob$1(CodelessInitExampleJob.scala:34)
     [java]     at za.co.absa.spline.example.batch.CodelessInitExampleJob$delayedInit$body.apply(CodelessInitExampleJob.scala:25)
     [java]     at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
     [java]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
     [java]     at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java]     at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java]     at scala.collection.immutable.List.foreach(List.scala:392)
     [java]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
     [java]     at scala.App$class.main(App.scala:76)
     [java]     at za.co.absa.spline.example.SparkApp.main(SparkApp.scala:27)
     [java]     at za.co.absa.spline.example.batch.CodelessInitExampleJob.main(CodelessInitExampleJob.scala)
     [java] 20/02/19 10:03:56 INFO SparkContext: Invoking stop() from shutdown hook
     [java] 20/02/19 10:03:56 INFO SparkUI: Stopped Spark web UI at http://158.175.78.42:4040
     [java] 20/02/19 10:03:56 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
     [java] 20/02/19 10:03:56 INFO MemoryStore: MemoryStore cleared
     [java] 20/02/19 10:03:56 INFO BlockManager: BlockManager stopped
     [java] 20/02/19 10:03:56 INFO BlockManagerMaster: BlockManagerMaster stopped
     [java] 20/02/19 10:03:56 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
     [java] 20/02/19 10:03:56 INFO SparkContext: Successfully stopped SparkContext
     [java] 20/02/19 10:03:56 INFO ShutdownHookManager: Shutdown hook called
     [java] 20/02/19 10:03:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-95098f49-5754-4b21-a624-565f023940e0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.705 s
[INFO] Finished at: 2020-02-19T10:03:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project examples: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /root/spline/examples/run-example.xml:36: The following error occurred while executing this line:
[ERROR] /root/spline/examples/run-example.xml:42: The following error occurred while executing this line:
[ERROR] /root/spline/examples/run-example.xml:59: The following error occurred while executing this line:
[ERROR] /root/spline/examples/run-example.xml:69: Java returned: 1
[ERROR] around Ant part ...<ant antfile="/root/spline/examples/run-example.xml">... @ 5:56 in /root/spline/examples/target/antrun/build-main.xml
[ERROR] -> [Help 1]

**Comment by Sequential-circuits** [comment]
Also, please be aware that the link at that page "The different examples are located here:

batch batchWithDependencies"  leads to page not found :)

**Comment by Zejnilovic** [comment]
Please do provide us with the way you ran the above. What were the steps to get there? (The Issue Bug template should help you with what we need)

**Comment by Sequential-circuits** [comment]
I just ran the command mvn test -P examples as the page says

**Comment by Zejnilovic** [comment]
Interestingly my run passes

```
mvn test -P examples                                                                                                        1 ↵

[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< za.co.absa.spline:examples >---------------------
[INFO] Building examples 0.4.1
[INFO] --------------------------------[ jar ]---------------------------------
...
...
...
spark-2d15c4ff-1460-4c1b-a865-83089d9ced25
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 min
[INFO] Finished at: 2020-02-19T11:26:43+01:00
[INFO] ------------------------------------------------------------------------
```

Could you confirm you have check out the `f56dfb25e51378a76bff64bf3fea2bca872a0049` 
or `git checkout release/0.4.1`

Will try to look into it further.

**Comment by Sequential-circuits** [comment]
If I go to the repo by entering cd spline and typing git checkout https://github.com/AbsaOSS/spline/tree/release/0.4.1 and is not working. Sorry but I suck with git

**Comment by Zejnilovic** [comment]
You should write `git checkout release/0.4.1` as I write (copy-paste it). The `release/0.4.1` is a tag that points to a stable commit of 0.4.1

**Comment by Sequential-circuits** [comment]
Actually, I had tried that and the result is fatal: not a git repository (or any of the parent directories): .git

Sorry for what I am sure its a silly question: like I said, I suck with git

**Comment by Zejnilovic** [comment]
It's ok. When you clone spline. You cd into spline folder and there you should do the `git checkout`

**Comment by Sequential-circuits** [comment]
That is exactly what I did :(

**Comment by Sequential-circuits** [comment]
Weird: I downloaded the project again and now the git checkout works. oh well :)

**Comment by Sequential-circuits** [comment]
ok, now the examples work. :)
