### ISSUE TITLE
Powered by Spline | v. 0.4.1 ERROR Server returned code: undefined, error message is: The URI is malformed. 

### ISSUE THREAD

**Issue by Sequential-circuits** [AbsaOSS/spline#596]
I am running the server with the command docker container run -e spline.consumer.url=http://`ipconfig getifaddr en0`:8081/consumer       -p 9090:8080       absaoss/spline-web-client as instructed elsewhere, but getting the message "Powered by Spline | v. 0.4.1 ERROR Server returned code: undefined, error message is: The URI is malformed. "

**Comment by cerveada** [comment]
Hi, I assume you are trying to run Spline UI, right? `spline.consumer.url` should actually be the same as your local consumer URL, the url is used from js app that will be running inside your browser, not from inside docker.

**Comment by Sequential-circuits** [comment]
actually, stupid of me. I thought I was supposed to use that address when it was actually a command in windows to get my ip. I use linux, so I used ifconfig, got the address, put it and it works now
