### ISSUE TITLE
Improve filter predicate visualization

### ISSUE THREAD

**Issue by vackosar** [AbsaOSS/spline#6]
![image](https://user-images.githubusercontent.com/11373934/30761711-7faf8d58-9fdf-11e7-9122-578ac19e99d3.png)
Improve operation visualization e.g. on picture above improve the way equation is visualized in bottom dialog section.

**Comment by vackosar** [comment]
# Proposal 1
- expanded tree view with lines highlighting relationships.
![image](https://user-images.githubusercontent.com/11373934/30771384-f393bd22-a046-11e7-8a3c-17c62ebb0d1a.png)
- Add symbol representation (icons) to operators.

**Comment by wajda** [comment]
Yep, let's try.

**Comment by vackosar** [comment]
Renamed to reflect more accurately the goal. Let me know if that is not what you expect.

**Comment by vackosar** [comment]
@wajda I am not sure how to add test data into db.js at the moment. I extracted lineages from mongo db, but they are still not getting displayed. (Getting 404 on `http://localhost:8080/rest/dataset/ln_e60b3245-e515-4d24-8cad-c5b82b5c1f37/lineage/overview`). Let me know if you have any hints.

**Comment by vackosar** [comment]
There is some issue with styling on tree in `ExpressionDialogComponent` causing e.g. losing CSS `::before content` with a button for expanding and collapsing. Not sure yet what is the problem.

**Comment by wajda** [comment]
> Getting 404 on http://localhost:8080/rest/dataset/ln_e60b3245-e515-4d24-8cad-c5b82b5c1f37/lineage/overview

Remove `ln_` prefix.

**Explanation:**
The give REST API operated with ID of datasets, not lineages.
Path `/dataset/:id` refers to a _dataset_, while `ln_:id` is an ID of a _lineage_ for a dataset with ID=`:id`
Lineage ID is synthetic and is derived from the ID of a dataset, that it represents. Lineage ID is implementational details. It's only used on the storage level and is not intended for any client API. Instead, alway refer lineage via it's related dataset. E.g. `/dataset/e60b3245-e515-4d24-8cad-c5b82b5c1f37/lineage/overview`

**Comment by vackosar** [comment]
Resolved ![image](https://user-images.githubusercontent.com/11373934/41766619-cb2883e4-7607-11e8-91a7-9b6582cb2897.png)
