### ISSUE TITLE
ElasticSearch connector support

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#606]
https://github.com/elastic/elasticsearch-hadoop

**Comment by radford1** [comment]
It looks like support for scala 2.12 is not quite ready for this

[https://discuss.elastic.co/t/elasticsearch-support-for-spark-2-4-2-with-scala-2-12/197810](url)
[https://github.com/elastic/elasticsearch-hadoop/issues/1224](url)

Is there a way we can limit this in spline-spark-agent?

**Comment by wajda** [comment]
That's unfortunate. Yes, we could limit ES support for Scala 2.11.
Let's create a new issue about adding support for ES + Scala 2.12 referring those issue above. 
And tag the test with a conditional `@Ignore` tag, like in the snippet below:
```scala
import za.co.absa.commons.version.Version._

it should "support ES" taggedAs ignoreIf(semver"${util.Properties.versionNumberString}" >= semver"2.12.0") in {
  // only run for Scala < 2.12
}
```

**Comment by radford1** [comment]
Created [#637](https://github.com/AbsaOSS/spline/issues/637) for tracking scala 2.12
