### ISSUE TITLE
How to stop casting of timezone

### ISSUE THREAD

**Issue by Qurashetufail** [AbsaOSS/spline#610]
Hi Team,

I am using Spline 0.4.2v. While running the script using oracle as a data source I am getting the lineage in the below format
![image](https://user-images.githubusercontent.com/22616149/76769968-33966780-67c3-11ea-9bdc-2cc3d42c3690.png)

But after running the same script using excel as a database I am getting the lineage in a different format
![image](https://user-images.githubusercontent.com/22616149/76769866-0d70c780-67c3-11ea-81cb-f643f62812ac.png)

Request you to please let me know how can I get the lineage in the format which I got from excel as a data source by keeping oracle as a database
I am not doing any transformation of this kind in my script.
Thanks,
Tufail

**Comment by wajda** [comment]
Hi @Qurashetufail,
Spline does not alter Spark jobs in any ways. Spline only reflects the logical execution plan that Spark has executed. Think about Spline as just a logger. It only sees what Spark let it to see.
So you need to look closer at your application and/or the other 3rd-party libraries that you might be using, e.g. Spark connectors.

**Comment by Qurashetufail** [comment]
I understand that Spline is just a logger but how it is providing the lineage in two different formats for a single spark job. Is it because of the Oracle driver that I am using in the second case? I am asking this because I am not using any other thing in my spark job. And can this be prevented from happening?

Thanks,
Tufail

**Comment by wajda** [comment]
Again, the questions is not related to Spline. For some reason your execution plan is different in both cases. I guess Oracle or Excel connector affects in in some way, but I cannot tell you how and why.

**Comment by Qurashetufail** [comment]
Thank you for the help @wajda. I will check the oracle and excel connector that I am using.
Thanks,
Tufail
