### ISSUE TITLE
Lineage Timestamp format is missleading

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#612]
## Describe the bug
Timestamp in the Lineage overview is misleading. Shows only hours up to 12 and no PM/AM

## Components State
- [x] ArangoDB running without errors
- [x] ArangoDB spline database initialized
- Rest Gateway running and
  - [x] connects to ArangoDB
  - [x] there are no errors in logs
- Spline UI running and
  - [x] connects to Rest Gateway consumer
  - [x] there are no errors in logs

## To Reproduce
1. Go to spline UI
2. Pick any lineage and open it
3. Look at the Left Panel timestamp

## Expected behaviour
I would expect to either have a 24h format or a PM/AM at the end.

#### This job was run at 17:10 or 05:10 PM
![image](https://user-images.githubusercontent.com/17467768/77041854-ea106d00-69ba-11ea-8168-41bba073520e.png)

**Comment by wajda** [comment]
Confirm. UI is using a strange time format. Should be 24h everywhere.

**Comment by Zejnilovic** [comment]
> Confirm. UI is using a strange time format. Should be 24h everywhere.

In that case. Dashboard need an update too
![image](https://user-images.githubusercontent.com/17467768/77064520-e93e0200-69df-11ea-86ec-aaab8ad376bf.png)

Don't know of any other places.

**Comment by Zejnilovic** [comment]
Works as expected
