### ISSUE TITLE
Prevent getting out of displayed lineage in embeddedMode

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/spline#613]
## Background
When Spline 0.4.x UI is displayed in embedded mode (`embeddedMode = true`), it's possible to navigate out of the requested lineage.

## Feature
Disable the "clickability" of components leading to overview or completely out of Spline, if `embeddedMode = true`.

## Example
![image](https://user-images.githubusercontent.com/14905969/77151695-c9b5e080-6a96-11ea-84a7-d78d611a2843.png)

**Comment by wajda** [comment]
We'll put a quick fix to the 0.5 release, but the 'embeddedMode` as it is, should be revised in #614

**Comment by benedeki** [comment]
0,5 release or 0.4, please?

**Comment by wajda** [comment]
let's discuss on Monday

**Comment by Zejnilovic** [comment]
Look good in Menas
