### ISSUE TITLE
Spline on an Arango production setup

### ISSUE THREAD

**Issue by rvvincelli** [AbsaOSS/spline#623]
## Describe the bug
Hi team, today we have successfully tested the Spline setup, it works, great!

We did lose a lot on time on the following issue - again, we might be missing something, so I am opening this as a bug but not sure it actually is one.

When deploying Arango as a production cluster, using the k8s operator they support, with [this](https://github.com/arangodb/kube-arangodb/blob/master/examples/production-cluster.yaml) template, the lineage overview call to the backend fails.

## Components State
- [ Y ] ArangoDB running without errors
- [ Y ] ArangoDB spline database initialized
- Rest Gateway running and
  - [ Y ] connects to ArangoDB
  - [ N ] there are no errors in logs
- Spline UI running and
  - [ Y ] connects to Rest Gateway consumer
  - [ Y ] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:

0. Setup Arango as with the operator above, I think it is a distributed mode cluster or something (not sure actually sorry)
1. Launch some dummy Spark job to create an entry; we are just doing something even more simple than your examples, like `sc.parallelize(list)` and subsequent Parquet write
2. Open the UI; the lineage entry appears correctly
3. Click on it; the lineage overview backend request will fail
4. The backend will complain that the registered UDFs Spline uses are missing `WITH` statements (as I read Arango requests since 3.1); but even adding them all over will result in a failure
5. In particular, even with the needed statements, the Arango transaction processor will complain that it is not permissible to with-lock the transaction, it throws [this](https://github.com/arangodb/arangodb/pull/9775/files#diff-c6dd12b7770ba7b4cde3a258f408ffdeR447) exception

Tested both on the latest-greatest (`0.4.2`) and trunk (`0.5.0-SNAPSHOT`).

## Expected behaviour
We would expect this to just work, as in: it would be cool if Spline would work no matter the Arango backend setup. We are now running our setup with the [single node](https://github.com/arangodb/kube-arangodb/blob/master/examples/single-server.yaml) cluster.

## Additional context
The cluster we use is an Azure Kubernetes Service one, latest.
This issue comes up with pretty much any new Arango version, but with 3.5.1 the error statement above was clear to read.

I have not saved the logs unfortunately, but it should be pretty easy to reproduce given the above.
As both the operator setups work on HTTPS, my pullreq from the other day is needed too (or HTTPS should be manually disabled in the Helm templates).

Should you need any info or help let me know. Thank you,

cc @patrickdehoon

**Comment by wajda** [comment]
cc @hamc17

**Comment by wajda** [comment]
Thanks Riccardo, 
I presume that it happens because of the current Spline limitation - we rely on ACID transactions that aren't supported for shared ArangoDB cluster. This is to be addressed in the future Spline versions. Meantime could you please use a single-shard? It's still possible to use replication however. Sharding is the problem.

**Comment by rvvincelli** [comment]
Hi @wajda , thanks for your prompt answer. OK, so if we use no sharding but replication, that should work, clear. This is OK I would say, If we get to try that out I'll beep you ;) Tx,
