### ISSUE TITLE
AVRO: a class name is captured instead of a format name

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#642]
Avro format is displayed as `org.apache.spark.sql.avro.AvroFileFormat@16c9ec5b`. Should be just `Avro`

**Comment by wajda** [comment]
@Zejnilovic

**Comment by radford1** [comment]
Any issues if I pick this up as another read/write source in the spline-spark-agent repo?

**Comment by radford1** [comment]
At second look this seems to be more involved than just simply adding it as another source

**Comment by wajda** [comment]
Hi David,
Yes, sure, you can do it. It should be easy too.
Avro is not a source type, but a data format. It doesn't require any specific handling like you did for Cassandra, ES etc, but just needed to be correctly converted to a string. Apparently Spline calls `toString()` method to get a format name, but `AvroFileFormat` doesn't seem to have it overridden. So we either need to find another generic way to get a format name instead of relying on `toString()` or just handle Avro format class differently like we did for data sources.

**Comment by wajda** [comment]
@radford1 As for another data source connector support you can pick #639, unless you mind exotic things :)

**Comment by radford1** [comment]
I actually used your cobrix library in the last year or two so I will gladly try to take that on! I'll also take a crack at this avro issue. It seems like we can add some case logic in this snippet to handle issues like this
`case cmd: InsertIntoHadoopFsRelationCommand =>
        val path = cmd.outputPath.toString
        val format = cmd.fileFormat.toString
        val qPath = pathQualifier.qualify(path)
        WriteCommand(cmd.nodeName, SourceIdentifier(Some(format), qPath), cmd.mode, cmd.query, cmd.options)`

**Comment by wajda** [comment]
Yep. And leave `toString` there as a default case.
