### ISSUE TITLE
JSON property view: expand/collapse

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#645]
![image](https://user-images.githubusercontent.com/795479/79923356-9ff52e00-8435-11ea-953d-db9525c0668c.png)

`Properties` JSON should be collapsible. By default, the 1st level should be expanded, 2nd and further layers should be collapsed.

**Comment by wajda** [comment]
+ display non-empty properties for `read` and `write` operations.

**Comment by DaimonPl** [comment]
Any chance to add it not only in json view, but also use full table name (database.table) in dependency graph?

**Comment by wajda** [comment]
Well, it's not that easy as it seems. Spline UI displays datasource URI, which in your case points to a Parquet file. The fact that the job actually read/wrote a Hive table mapped to a Parquet is specific to that exact job/cluster setup, and the UI has no knowledge of it.
I think what you need can be implemented by setting a custom user-friendly name for certain datasources, with which it would be displayed in the lineage graphs. Currently Spline doesn't have this feature, but in it will be added in a future version together with datasource management. I created an epic for this - #689
But for now displaying the database and table as properties of read/write operations is the only way.

**Comment by oleksandr-korchak** [comment]
- Display all extra fields which are in the properties object after the known.
Props which are object  or array should be displayed as an extra section.
Section is collapsed by default for data types which are array or object.

Known properties for 

General visible props:
- name (shown at the top)

General Hidden
- 
Logical Relation:

- inputSources
- sourceType

Write:
- outputSource
- destinationType
- append
