### ISSUE TITLE
Attribute search could respect selected time frame

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#649]
## Background
When people search for attributes it is quite easy to exceed the 10 attributes limit in search. For this, I think the attribute search bar should respect the selecting time frame.

## Feature
Attribute toolbar respects the time frame selected
Attribute toolbar moved bellow the date picker

**Comment by wajda** [comment]
Closing as obsolete.
UI module has been moved to a separate project - https://github.com/AbsaOSS/spline-ui
Attribute search in its variant of the time when this issue has been created, has also been removed from the current UI due to the poor usability.
