### ISSUE TITLE
Selected node not properly visible when attribute search for

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#650]
## Describe the bug
When I search for attribute and select one I would expect that the node with selected attribute would be more visible (like when I click on it) and even maybe. selected on the left panel.

## Components State
- [x] ArangoDB running without errors
- [x] ArangoDB spline database initialized
- Rest Gateway running and
  - [x] connects to ArangoDB
  - [x] there are no errors in logs
- Spline UI running and
  - [x] connects to Rest Gateway consumer
  - [x] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Search for attribute
2. Select a random one
3. See the issue

## Expected behaviour
- selected node more visible
- selected node is shown on the left panel

## Screenshots
![image](https://user-images.githubusercontent.com/17467768/79996040-43872280-84b8-11ea-8c09-2e495e91ac1e.png)

**Comment by wajda** [comment]
Options to consider:
1. Select the operation of origin by default (if we stay on this page)
2. Navigate to a new _attribute graph_ page instead of this one

**Comment by wajda** [comment]
fixed in #660
