### ISSUE TITLE
Transformations view enhancment

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#651]
## Background
When I select a transformation I get a modal window with the transformation but it has no header and the expand buttons are just boxes
![image](https://user-images.githubusercontent.com/17467768/79996774-1d15b700-84b9-11ea-89fb-8d2acedc35ef.png)

## Feature
- Add a header to the transformation detail
- Switch the expand buttons for something like a down-facing arrow and right-facing arrow

**Comment by wajda** [comment]
![image](https://user-images.githubusercontent.com/795479/84424175-fd308300-ac1f-11ea-967b-ae8a3ab5fb89.png)
