### ISSUE TITLE
Command to start arangodb on the documentation

### ISSUE THREAD

**Issue by deeptibaghel** [AbsaOSS/spline#655]
## Background
Command to start arangodb on https://absaoss.github.io/spline/ is not there.

## Feature
Steps to start arangodb should be specified.

## Proposed Solution 
Solution Ideas 
1.   docker run -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb
2.   docker run -e ARANGO_NO_AUTH=1 -p 8529:8529  arangodb

**Comment by wajda** [comment]
it's there
![image](https://user-images.githubusercontent.com/795479/101846980-6dc64700-3b52-11eb-8654-11525840b5a9.png)
