### ISSUE TITLE
Upgrade domain model to accommodate attribute level lineage requirements

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#677]
Introduce _schema_, _attribute_ and _expression_ nodes.

**Comment by pratapmmmec** [comment]
@wajda Wanna check if this model will give us the capability to build forward lineage in future without need of tweaking persistence model again. If yes, then I am assuming we only need to build API and UI to enable forward lineage in Spline.

**Comment by wajda** [comment]
This is still a work-in-progress feature, but yes, we are going there.
Spline 0.6 will come with a attribute level lineage support on the persistent model level. It should give a solid tool to create/query  different representation of linage with different level of details depending on the use-case.
We'll also change Consumer API accordingly to expose those new abilities over the REST API and subsequently the UI
