### ISSUE TITLE
Looks like its not supporting sql command queries

### ISSUE THREAD

**Issue by uday1409** [AbsaOSS/spline#679]
Merge queries in delta databricks /creating persistent table using spark sql queries is not being tracked in lineage. It sasys"Skipping lineage tracking for command". Is this expected? Appreciate your response.

**Comment by cerveada** [comment]
There are some commands that are not currently supported. The plan is to eventually support everything, but we don't have the capacity to do it right now.

you can see what is supported or not in Spark Agent readme:
https://github.com/AbsaOSS/spline-spark-agent

**Comment by uday1409** [comment]
Thanks for your response, Adam. 

Could you please tell us the need /motivation behind moving from Mongo to ArangoDB.

**Comment by cerveada** [comment]
That's more of a question for Alex @wajda

**Comment by wajda** [comment]
It's not related to the topic. Moving to a graph storage was a fundamental architectural decision. ArangoDB was chosen based on evaluation of different criteria.

**Comment by uday1409** [comment]
Thanks @wajda @cerveada . Could you please guide me if there is any discussion forum as I have few questions related to using this in my project

**Comment by wajda** [comment]
@uday1409, we don't have any dedicated forum or such I'm afraid. GitHub seems to be testing a new "Discussions" tab, that looks promising, but is not there yet.
For now simply use "Issues". Just create a new issue selecting "Question" type in the template and start your discussion topic.
