### ISSUE TITLE
Lineage Overview UI - directed graph

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline#686]
I think it would be easier to read if dependency graph in "Lineage Overview" would display arrows instead of straight lines.

In some specific dependency scenarios (dependency sharing between multiple jobs which output is used for other job) UI is not 100% clear about direction of dependencies

**Comment by wajda** [comment]
Valid point. Actually the arrows used to be there before, but somehow disappeared at some stage.

**Comment by wajda** [comment]
@oleksandr-korchak, in addition to this we need display some sort of warning when the length of the overview graph hits the threshold, until the issue #399 is fixed.
Currently maximum 10 hops are queried - https://github.com/AbsaOSS/spline/blob/release/0.5.1/client-ui/src/app/effects/lineage-overview.effects.ts#L56
