### ISSUE TITLE
Spline Gateway index page

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#697]
Currently, the root url on spline gateway returns 404. It would be more user-friendly to put there some info about the Gateway.

There could be application status, a link to producer and consumer, link to swagger documentation, link to database and more.

**Comment by wajda** [comment]
What else do we need to put on the page?

![image](https://user-images.githubusercontent.com/795479/84055899-bf302680-a9b5-11ea-8121-02f295d81032.png)
