### ISSUE TITLE
What are spline docker images default catalina/tomcat settings?

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline#701]
I'm looking if spline docker images are good enough for simple single instance setup for smaller projects.

Where can i find default settings for catalina/tomcat used in those images?

How can i change those settings?

Sorry for noob questions but I haven't used catalina/tomcat images before :)

**Comment by wajda** [comment]
https://github.com/AbsaOSS/spline/blob/release/0.5/rest-gateway/Dockerfile
We use all defaults.

**Comment by DaimonPl** [comment]
Ok, clear, thx :)

**Comment by hamc17** [comment]
> Where can i find default settings for catalina/tomcat used in those images?


Running the command `docker exec -it container_name bash` will give you the terminal on the running container. The configuration files for tomcat are under `/usr/local/tomcat/conf`.

> How can i change those settings?


If you have your own config files, e.g. server.xml, catalina.properties, etc, you can overwrite them by adding the following line to the Dockerfile:
`COPY /path/to/local/config/file/file.ext /usr/local/tomcat/conf/file.ext`, replacing paths as required.
