### ISSUE TITLE
Is MongoDB supported for newer Spline versions?

### ISSUE THREAD

**Issue by aravish** [AbsaOSS/spline#722]
## Background [Optional]
We are trying to use Azure Cosmos DB (Mongo API) with Spline, but it doesn't seem to be working.

Some of the docs say below, just wanted official confirmation if MongoDB is still supported. Thanks
Spline 0.3 was running with mongoDB. In Spline 0.4 ArangoDB was introduced. To migrate the data from mongoDB to ArangoDB,

## Question
Is MongoDB supported for newer Spline versions? If not when was this support deprecated?

**Comment by cerveada** [comment]
Hello, 
MongoDB is not supported in newer versions. From version 0.4 Spline requires ArangoDB.

**Comment by cerveada** [comment]
I updated the documentation to make this more clear.
