### ISSUE TITLE
Visible URL to detailed lineage

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline#732]
It would be good if UI would additionally display URL to detailed lineage of job.

It took me really a while to realize that double click on job on graph has some action :D

**Comment by wajda** [comment]
:facepalm: man, where have you been yesterday? :laughing: Now I need to release a new version of the entire project just to add
```<a href="..." >Show detailed lineage</a>```

**Comment by DaimonPl** [comment]
I think it can safely wait for other changes :)

**Comment by wajda** [comment]
+ fixed breadcrumbs navigation
