### ISSUE TITLE
Spline Web UI-  "ERROR Server returned code: 0. Http failure response for http://spline:9090/consumer/execution-events"

### ISSUE THREAD

**Issue by ankit302** [AbsaOSS/spline#744]
## Describe the bug
While accessing Spline web UI - getting server retured code:0 https failure response.

## Versions
spline version 0.5.3 ( Docker latest image tag )
arnagoDb version 3.5.1 ( Docker latest image tag )

## Components State
- [ Yes ] ArangoDB running without errors
- [ Yes] ArangoDB spline database initialized
- Rest Gateway running and
  - [YES ] connects to ArangoDB
  - [ YES] there are no errors in logs
- Spline UI running and
  - [NO ] connects to Rest Gateway consumer
  - [YES ] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:

Accessing spline webui on brower 

## Expected behaviour
Should be able to view the spline webUI page

## Screenshots
Attached the error of spline webUI:
![Capture](https://user-images.githubusercontent.com/28657492/86009391-cb008d00-ba37-11ea-98dd-4900e7d00627.PNG)

## Desktop (please complete the following information):
- OS: [Ubuntu]
- Browser [Chrome]
- Version [Latest]

## Additional context

spline service file:-

apiVersion: v1
kind: Service
metadata:
annotations:
kompose.cmd: kompose convert
kompose.version: 1.21.0 (992df58d8)
creationTimestamp: null
labels:
io.kompose.service: spline
name: spline
namespace: dataservice
spec:
ports:

service file spline-ui:-

name: "9090"
port: 9090
targetPort: 8080
selector:
io.kompose.service: spline
status:
loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
annotations:
kompose.cmd: kompose convert
kompose.version: 1.21.0 (992df58d8)
creationTimestamp: null
labels:
io.kompose.service: ui
name: spline-ui
namespace: dataservice
spec:
ports:

name: "8080"
port: 8080
targetPort: 8080
selector:
io.kompose.service: ui
status:
loadBalancer: {}

**Comment by wajda** [comment]
Answered here - https://github.com/AbsaOSS/spline/issues/743#issuecomment-651109409

**Comment by ankit302** [comment]
Hi @wajda ,

when i'm trying to access the endpoint (http://spline:9090/consumer/execution-events), getting below logs in 

13:26:06.868 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 94 ms
13:43:10.968 [http-nio-8080-exec-3] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:44:43.722 [http-nio-8080-exec-4] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:44:55.475 [http-nio-8080-exec-5] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:45:19.750 [http-nio-8080-exec-6] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:45:58.540 [http-nio-8080-exec-7] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:48:46.892 [http-nio-8080-exec-8] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:48:55.867 [http-nio-8080-exec-10] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:49:25.673 [http-nio-8080-exec-1] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:49:44.723 [http-nio-8080-exec-3] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
13:50:10.287 [http-nio-8080-exec-4] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /producer
13:50:48.994 [http-nio-8080-exec-6] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer

does spline.consumer.url should be "http://spline:9090/consumer/execution-events" or " http://spline:9090/consumer"

do you think It could be port mapping issue/forwarding issue.

**Comment by wajda** [comment]
try http://spline:9090/consumer/execution-events

**Comment by ankit302** [comment]
Hi @wajda ,

I even tried to setup on docker environment, with the latest version of spline, arangodb image from docker hub, But issue persist.

It appears to be an issue with the image;

Used docker compose file from github;
https://raw.githubusercontent.com/AbsaOSS/spline/develop/docker-compose.yml.


ankit@dockervm:~$ sudo docker ps -a
CONTAINER ID        IMAGE                        COMMAND                   CREATED             STATUS              PORTS                              NAMES
27010ecc9c61        absaoss/spline-web-client    "catalina.sh run"         3 hours ago         Up 3 hours          8009/tcp, 0.0.0.0:8080->8080/tcp   ankit_ui_1
99c0a5d6108d        absaoss/spline-rest-server   "bash -c '\n  until c…"   3 hours ago         Up 3 hours          8009/tcp, 0.0.0.0:9090->8080/tcp   ankit_spline_1
8c3c24d580de        arangodb                     "/entrypoint.sh aran…"    3 hours ago         Up 3 hours          0.0.0.0:8529->8529/tcp             ankit_arangodb_1
 

When tried to access the spline.consumer.url  using curl (curl http://localhost:8080/consumer)

29-Jun-2020 15:14:14.089 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
29-Jun-2020 15:14:14.101 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
29-Jun-2020 15:14:14.104 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [7,848] milliseconds
**15:18:07.787 [http-nio-8080-exec-1] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /consumer
15:26:00.464 [http-nio-8080-exec-2] WARN  o.s.web.servlet.PageNotFound - No mapping for GET /producer**

**Comment by wajda** [comment]
You are trying a wrong URL

http://localhost:8080/consumer -- this resource does not exist
http://localhost:9090/consumer/execution-events -- this one does

**Comment by dhiraj-raj** [comment]
Hi @wajda  we tried this URL also i.e. http://localhost:9090/consumer/execution-events , but Spline-UI shows same error message as indicated above.

**Comment by wajda** [comment]
I have answered it about 3 times already - the consumer REST API URL has to be accessible from the client browser. If Spine UI says "Code 0" it mean it cannot connect to that URL. Please double check your Spline setup.

**Comment by ankit302** [comment]
HI Wajda,

i understand that, URL is not accessible from splineUI.

we have used same Dockercompose file to run spline WebUI, rest server & arangodb without any modification.
https://raw.githubusercontent.com/AbsaOSS/spline/develop/docker-compose.yml

Do you see ant issue with config parameters in docker compose file ?

Does any one else facing similar issue ?

**Comment by wajda** [comment]
Ah, that's a new piece of info. Seems like an issue with the Docker. Just tried our `doker-compose.yml` and the 'spline' container appeared to have connection issues. Re-opening the issue, although I have doubts that it's related to Spline, rather to a Docker network config.

**Comment by wajda** [comment]
I have just confirmed that it is indeed a particular docker setup issue that has nothing to do with Spline. 
I've tested it on three PCs running Fedora, Ubuntu and MacOS, the same Dcoker version 19.03.8. Only on my Fedora PC I have this issue, on the other two laptops docker-compose run Spline with no issue, straight out of the box.
So please check your docker network configuration and consult with the Docker support.
I consider this issue closed.
