### ISSUE TITLE
Where can I find spline log file for client-web.war deployed on tomcat

### ISSUE THREAD

**Issue by pratapmmmec** [AbsaOSS/spline#748]
I am getting some error on UI while accessing attribute level lineage.

I am unable to find any logs related to spline under tomcat/logs directory. Do I need set some args explicitly for that?
Have attached screenshot of error for reference
<img width="1550" alt="Screenshot 2020-07-03 at 4 14 20 PM" src="https://user-images.githubusercontent.com/67417754/86462342-1ae99780-bd49-11ea-84ae-70e30089fba3.png">

**Comment by cerveada** [comment]
client-web.war is only thin wrapper around angular application. What you should look for is log for spline gateway war. That's the server that is returning you 500.

**Comment by pratapmmmec** [comment]
Thanks @cerveada . I was able to find logs for spline gateway war. Had forgot to close it. Doing it now

**Comment by wajda** [comment]
@pratapmmmec from your screenshot above I see that you have a quite complex execution plan. Can I ask you for a favor? Could you  possibly share a job that generates such plan? It would serve as a pretty much interesting test case for us to tune the graph view and other aspects of the Spline UI. If it's a commercial closed code then perhaps you can share a sanitized version of it (renamed attributes, file names etc). The graph structure is important, not the meaning of the operations.

**Comment by pratapmmmec** [comment]
@wajda Considering company policy, I can't share the SQL as is. I am yet to hear from my org's Open Source Group on masking columns and table names in SQL and sharing here. Give me couple of days and I will confirm. Hopefully it should not be a problem

**Comment by pratapmmmec** [comment]
@wajda Just to keep you posted. It might take another week or so as it needs to go through few levels of approval.

**Comment by wajda** [comment]
Sure, no rush :) Thanks for the info.
