### ISSUE TITLE
documents_spline_1 exited with code 6 when running docker-compose up

### ISSUE THREAD

**Issue by ASchwad** [AbsaOSS/spline#765]
## Describe the bug
When i run docker-compose up with the suggested docker-compose.yml, `documents_spline_1` exits with code 6 and i cannot track the Lineage. If i try to restart the failed `documents_spline_1` container, it stops right away again. 
The UI is running fine and gets the following error: `GET http://localhost:9090/consumer/execution-events?sortOrder=desc&sortField=timestamp&pageNum=1&asAtTime=1598278683141 net::ERR_EMPTY_RESPONSE`

I also tried to change the port in docker-compose.yml from 9090 to 9091 at both occurrences - but without success.

## Components State
- [x] ArangoDB running without errors
- [x] ArangoDB spline database initialized
- Rest Gateway running and
  - [ ] connects to ArangoDB
  - [ ] there are no errors in logs
- Spline UI running and
  - [ ] connects to Rest Gateway consumer
  - [ ] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Get docker-compose.yml
2. run docker-compose up

## Expected behaviour
I expected , that all 3 container start successfully.

## Desktop (please complete the following information):
- OS: macOS Catalina, Version 10.15.5

**Comment by cerveada** [comment]
It looks like that yaml file was not updated, try to use the one in developer branch:
`https://raw.githubusercontent.com/AbsaOSS/spline/develop/docker-compose.yml`

**Comment by ASchwad** [comment]
Thanks for the quick reply!

With your changes, i get a different behaviour. Now the arangodb is having problems. This is the error log when I run `docker-compose up `

`spline_1    | waiting for arango db
arangodb_1  | 2020-08-25T07:05:50Z [1] INFO [e52b0] ArangoDB 3.7.1 [linux] 64bit, using jemalloc, build tags/v3.7.1-0-gdd98295dcc, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1g  21 Apr 2020
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [75ddc] detected operating system: Linux version 4.19.76-linuxkit (root@4abe09437d05) (gcc version 8.3.0 (Alpine 8.3.0)) #1 SMP Tue May 26 11:42:35 UTC 2020
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [25362] {memory} Available physical memory: 2087837696 bytes, available cores: 4
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [43396] {authentication} Jwt secret not specified, generating...
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [144fe] using storage engine 'rocksdb'
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [3bb7d] {cluster} Starting up with role SINGLE
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [6ea38] using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
arangodb_1  | 2020-08-25T07:05:51Z [1] INFO [3844e] {authentication} Authentication is turned off, authentication for unix sockets is turned on
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [3bc7f] {startup} Database directory version (30501) is lower than current version (30701).
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [ebca0] {startup} ----------------------------------------------------------------------
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [24e3c] {startup} It seems like you have upgraded the ArangoDB binary.
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [8bcec] {startup} If this is what you wanted to do, please restart with the
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [b0360] {startup}   --database.auto-upgrade true
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [13414] {startup} option to upgrade the data in the database directory.
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [24bd1] {startup} ----------------------------------------------------------------------'
arangodb_1  | 2020-08-25T07:05:51Z [1] ERROR [1c156] Database '_system' needs upgrade. Please start the server with --database.auto-upgrade
arangodb_1  | 2020-08-25T07:05:51Z [1] FATAL [2eb08] Database '_system' upgrade failed (bad parameter). Please inspect the logs from the upgrade procedure and try starting the server again.
spline_1    | waiting for arango db
documents_arangodb_1 exited with code 1`

So there seems to be a version mismatch: Database directory version (30501) is lower than current version (30604).

I tried changing the Arango Version in the .env down to 3.5.1. The DB launches successfully, but then i am back to the old behaviour, that the gateway does not start.

**Comment by ASchwad** [comment]
@cerveada  Thanks for your quick reply!

When running your suggested setup, the container seems to fail in this step:
``` 
spline_1    | downloading admin-cli documents_spline_1 exited with code 6
documents_spline_1 exited with code 6
```

**Comment by cerveada** [comment]
The database error: Is it possible that you left the old arango container in docker and that caused the incompatibility?
Have you called `docker-compose down`? Before using the new config?

**Comment by ASchwad** [comment]
Yes, I deleted the old container. I think this is a network issue at my company and not Spline related. The documents_spline_1 does not seem to be able to run 
`curl -O -s https://repo1.maven.org/maven2/za/co/absa/spline/admin/${SPLINE_VERSION}/admin-${SPLINE_VERSION}.jar -4` due to missing firewall and proxy settings.
