### ISSUE TITLE
Error while setting up Spline Server: java.net.MalformedURLException

### ISSUE THREAD

**Issue by amitguptaddn** [AbsaOSS/spline#766]
## Question
I am setting up Spline Server in local using instructions on this link: https://absaoss.github.io/spline/

Under section "Start Spline Server", I am using second option - "Java compatible Web-Container (e.g. Tomcat)"

Question: Please suggest where exactly to add the Arango connection string:
Add the argument for the ArangoDB connection string
`-Dspline.database.connectionUrl=arangodb://localhost/spline`

I have added in the file: apache-tomcat-9.0.37\webapps\rest-gateway-0.5.3\META-INF\context.xml and connection string looks like below:
```xml
<Environment override="true" type="java.lang.String" value="arangodb://root:@localhost:8529/spline" name="spline/database/connectionUrl"/>
```
Also, my Arango DB is up and running with username(root) and no password.

When I start Tomcat and try to run the application "rest-gateway-0.5.3" using the jar present here(https://repo1.maven.org/maven2/za/co/absa/spline/rest-gateway/0.5.3/rest-gateway-0.5.3.war)
it gives me below error:
```
Caused by: java.net.MalformedURLException: arangodb://root:@localhost:8529/spline (of class java.lang.String)
        at za.co.absa.spline.persistence.ArangoConnectionURL$.apply(ArangoConnectionURL.scala:83)
        at za.co.absa.spline.persistence.ArangoRepoConfig$Database$.<init>(ArangoRepoConfig.scala:58)
        at za.co.absa.spline.persistence.ArangoRepoConfig$Database$.<clinit>(ArangoRepoConfig.scala)
        ... 56 common frames omitted
```

**Comment by amitguptaddn** [comment]
Additional dependencies added in the pom.xml are below:

        <dependency>
            <groupId>com.arangodb</groupId>
            <artifactId>arangodb-java-driver</artifactId>
            <version>6.6.3</version>
        </dependency>
        <dependency>
            <groupId>com.arangodb</groupId>
            <artifactId>velocypack-module-scala_2.12</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-java8-compat_2.12</artifactId>
        </dependency>
    </dependencies>

**Comment by wajda** [comment]
You don't need `:` symbol after the username if your password is empty. Use `arangodb://root@localhost:8529/spline`
