### ISSUE TITLE
Introduce an AffectsDataSrc And DependsDataSrc  Endpoint

### ISSUE THREAD

**Issue by mohanajuhi166** [AbsaOSS/spline#793]
## Background
We have the existing collections - dataSource and executionPlan in **arangodb** collections. There is a small opportunity to introduce a minor feature, which can provide us the information on - which dataSources are affected and on which datasources its is dependent. 

## Feature & Proposed Solution
We have two ways of doing it - 

**Option 1**
We can create a new graph called affectsGraph  - with the following
@From - executionPlan
@To - DataSource

And then using the above graph for query. 

Example : 
```aql
FOR v,e,p IN INBOUND 'dataSource/<id>' GRAPH 'affectsGraph'
    RETURN DISTINCT v.extra.appName
```

**Option 2**
Introduce a new controller and new repository implemention - called affectsRepositoryImpl.scala 
using the below query
```aql
FOR e IN executionPlan, a IN affects OUTBOUND @dataSrc GRAPH 'affectsGraph'
    PRUNE a._to == @dataSrc AND e._id == a._from
    RETURN DISTINCT e.extra.appName
```
## Example 
<img width="873" alt="git_spline" src="https://user-images.githubusercontent.com/19162354/96572193-2c4fb300-12ea-11eb-8913-9d03f2400fd0.png">

Referring to the image above as example

The dependsDataSrc endpoint will return **WF_READ_1 & WF_READ_2**
The affectsDataSrc endpoint will return **WF_WRITE_1**
For the same,I would like to propose a minor feature addition for which I have coded the solution and would like to raise a pull request.

Kindly let me know your thoughts on the same.

**Comment by wajda** [comment]
Hi @mohanajuhi166,
Let me understand your proposal. You said the goal is to track the dependencies between execution plans and data source, and for that you propose to introduce another graph. How are your edges would differ from existing `depends` and `affects` edges that have the very same purpose?

**Comment by mohanajuhi166** [comment]
Hi @wajda , thanks a lot for replying. I tried the option 1 (creating a graph) to use pruning condition and potentially a run time complexity reduction but I am not very sure of the same. 

I would like to propose the option 2 - which is introducing two endpoints. to provide the information on dependant and affected workflow. This includes a repository implementation with calling query inside **consumer-rest-core**

Let me know your thoughts on the same.

**Comment by wajda** [comment]
That makes sense.
Let's use the following resource URLs:
-  `/execution-plans/{plan_id}/data-sources` -- a collection of _data sources_ directly associated with the given _execution plan_
-  `/data-sources/{ds_id}/execution-plan-ids` -- a collection of the _execution plan_ IDs directly associated with the given `data source`.

Both resources could be further filtered by the _access type_. i.e. read/write.

Example:
`/execution-plans/{plan_id}/data-sources?access=read` -- returns an array of input data sources of the given exec plan.
`/data-source/{ds_id}/execution-plan-ids?access=write` -- returns an array of the exec plans that writes into the given source.

**Comment by mohanajuhi166** [comment]
thanks @wajda , I will make the necessary changes. Do I need to do anything more to raise a PR?

**Comment by mohanajuhi166** [comment]
Implemented the following function inside executionPlanRepositoryImpl

```scala
val writeResult = db.queryStream[String](
      """
        FOR d IN dataSource
        |FOR a IN affects
        |FILTER a._from == @planId AND a._to == d._id
        |RETURN d.uri
        |"""
        .stripMargin,
      Map(
        "planId" -> "executionPlan".concat("/").concat(value)
      )
    )

    val readResult = db.queryStream[String](
      """
        FOR d IN dataSource
        |FOR dp IN depends
        | FILTER dp._from == @planId AND dp._to == d._id
        |    RETURN d.uri
        |"""
        .stripMargin,
      Map(
        "planId" -> "executionPlan".concat("/").concat(value)
      )
    )
```

**Comment by wajda** [comment]
Please go ahead and create a PR. One of our team members will review it.

**Comment by mohanajuhi166** [comment]
@wajda do I need write access to spline repo? I was trying to push my local branch. Not sure, hence asking.
