### ISSUE TITLE
Liveness and readiness probes

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#813]
**Liveness probe:**
  - CAN lead to container _restart_ if failed
  - SHOULD only examine the app itself and it's ability to process the queries
  - MUST NOT consider external dependencies (database etc)
  - SHOULD focus on detecting deadlocks, livelocks, starvation, and OOM errors
  - SHOULD respond quickly with low variation in response time.

**Readiness probe:**
  - CAN lead to container _disconnection_ if failed
  - SHOULD check if the app is warmed up and is ready to accept traffic
  - SHOULD NOT consider external shared dependencies, but CAN consider private external dependencies
  - SHOULD setup maximum possible timeout for checking external dependencies, and be conservative in failures

**Comment by wajda** [comment]
@dvagapov

**Comment by dvagapov** [comment]
Added Probes in native Kubernetes-style. Soon will be published official Deployment for Kubernetes using Helm-charts

**Comment by wajda** [comment]
At the moment there is nothing that we could additionally check with the probs.
Both probs return `200 OK` as long as the Spring context is up, which means all required config props are defined and the app is ready to serve requests. 
It automatically satisfies the _readiness_ prob. And for the _liveness_ there is no global app specific resource that needs to be additionally monitored (excepts to the database which is excluded from the probe anyway)

If more sophisticated checks are needed they will be implemented in separate tickets.
