### ISSUE TITLE
Consumer REST: Add "name" field for "DataSource" with sorting capabilities

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#843]
`GET /execution-events`
`GET /data-source`
should have sortable "name" field, that is derived from the "dataSourceURI" by cutting on the last meaningful slash

fyi, @oleksandr-korchak

**Comment by oleksandr-korchak** [comment]
@wajda maybe it is better to call it `dataSourceName`?

**Comment by wajda** [comment]
Makes sense for now, especially as both are sharing the same entity at the moment.
