### ISSUE TITLE
Rename package: za.co.absa.spline.producer.kafka` to `za.co.absa.spline.gateway.kafka` for consistency with the REST gateway

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#846]

**Comment by cerveada** [comment]
It makes sense, but it's not 100% consistent either way. Rest-gateway provide bot producer and consumer APIs, whereas kafka-gateway provides only producer API.

**Comment by wajda** [comment]
That's right, but those are different types of gateway. We could have one configurable gateway that could run an arbitrary number of services, like Kafka producer, REST producer and REST consumer. In that case Kafka module would only consist of Kafka specific classes and we'd call it like `producer-kafka-core` or something (similar to the modules that contain REST specific stuff).
But since we split it on the web container level, and Kafka module actually is a WAR that is similar to the rest-gateway in that regard, it makes more sense to call it `gateway` respectively. 
If you want to be picky, let's create two packages - one `gateway.kafka` is for keeping `AppInit` and `GatewayConfig` classes in there, and the other one `producer.kafka` to keep the listeners respectively :) Both in one module

**Comment by wajda** [comment]
will be done in scope of #831
