### ISSUE TITLE
Regarding Capturing of Input DataSource : Schema & TableName

### ISSUE THREAD

**Issue by mohanajuhi166** [AbsaOSS/spline#882]
Hi @wajda 
Greetings for the day.

I had one question .So in our execution workflows, the starting node captures only the location uri of the datasource (either GCS bucket entire path/hive path) but we dont get to see the the actual schema and table name. I think it only picks up the name from the last string of the location path.

Questions
1. Is my understanding correct?
2. Is there a way to capture schema and table name in dataSource collection, along with uri? 
Thanks & Regards,
Mohana

**Comment by wajda** [comment]
Can you send me the execution plan JSON? (write operation part is enough)

**Comment by mohanajuhi166** [comment]
@wajda sure. below . I have put dummy data but this is the way it is coming(removed actual names)
As you can ,see for gs://AABBCC2/ , we only get location uri of datasource but no info on table,schema;

```json
{
  "executionPlan": {
    "_id": "56978067-3289-451b-a5f8-2c02902c40fc",
    "systemInfo": {
      "name": "spark",
      "version": "2.3.0.2.6.5.279-2"
    },
    "agentInfo": {
      "name": "spline",
      "version": "0.5.1"
    },
    "extra": {
      "appName": "WORKFLOW",
      "dataTypes": [],
      "attributes": []
    },
    "inputs": [
      {
        "sourceType": "ORC",
        "source": "**gs://AABBCC2/**"
      }
    ],
    "output": {
      "sourceType": "ORC",
      "source": "**gs://AABBCC2/schema/table_name**"
    }
  },
  "graph": {
    "nodes": [],
    "edges": []
  }
}
```

**Comment by wajda** [comment]
That's JSON from the UI. But I'm interested in the JSON that your agent sends to the Spline server. Can you capture that one?

**Comment by mohanajuhi166** [comment]
@wajda ,how can i get that via the api ? or do i need to debug the application locally?

**Comment by wajda** [comment]
Which agent version are you using?

**Comment by mohanajuhi166** [comment]
0.5.5

**Comment by wajda** [comment]
For that version you have three options:
1. Enable TRACE log level and search logs for the phrase "sendJson"
2. Configure HTTP proxy for the agent.
Add the following JVM properties to the Spark agent process
```-Dhttp.proxyHost=... -Dhttp.proxyPort=... -Dhttp.nonProxyHosts=```
3. Debug the agent - class `HttpLineageDispatcher` line 158

**Comment by wajda** [comment]
Also, can you share how the write command looks like in you Spark job code?

**Comment by mohanajuhi166** [comment]
sure 
its 
`val spark=SparkIOUtil.getSparkSession()
    SparkLineageInitializer.enableLineageTracking(spark)`

**Comment by wajda** [comment]
I mean, I'd like to see the write command, how do you store the result data.

**Comment by mohanajuhi166** [comment]
@wajda sorry a little confused, do you mean the writeTo collection?
Because we just followed the list of steps here : https://absaoss.github.io/spline/

**Comment by wajda** [comment]
No I mean your Spark SQL code. What Spark operation you perform.

**Comment by mohanajuhi166** [comment]
sure, I will share it in sometime, thanks !

**Comment by mohanajuhi166** [comment]
@wajda we can close this, this was an issue at our end, Thank you
