### ISSUE TITLE
Make Docker images size smaller

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#889]
Since more and more people are using Docker containers over standalone J2EE servers, I see no reason to continue supporting the later. We should switch to a lighter container (Spring boot?).

**Comment by cerveada** [comment]
Spring boot packages a tomcat inside the jar that it creates. Isn't it actually more bulky?

I am not saying that it's a bad idea, but what is the goal here?

**Comment by wajda** [comment]
Oh, does it? So I didn't put that question mark for nothing :)) For some reason I thought Spring boot had its own http engine.
Maybe Play! then? We don't depend on Spring much anyway. I think any decent alternative would work. We need to do some research on this topic when we have time.

**Comment by wajda** [comment]
Just to clarify. I'm not against WAR-files, in fact I see a lot of strengths in this tech. I'm just wandering if there is anything more modern and significantly more lightweight in the micro-services and Docker era. But by default I'd stick with the current stack.

**Comment by cerveada** [comment]
As far as I know Spring boot doesn't add many new features to spring. It mostly provides opinioned default configuration for all other spring parts that makes everything work out of the box.

In Boot, you can choose Tomcat, Jetty or Undertow as a servlet container.

An interesting alternative to Spring-MVC might also be [Spring Web Reactive](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#spring-webflux). Which claims to be functional and fully asynchronous. Spring Web Reactive by default runs on all mentioned servers plus on Netty server.

**Comment by wajda** [comment]
As it turns out Tomcat slim image is already quite compact where the largest part is the OS layer. So no further image size optimization is needed at this stage IMO

**Comment by wajda** [comment]
I'll replace JDK with JRE and use `-slim` base image
