### ISSUE TITLE
J2EE artifacts deployment was failed

### ISSUE THREAD

**Issue by picomy** [AbsaOSS/spline#943]
## Background [Optional]
I deployed the spline 0.6 by J2EE artifacts in Jetty 11. The rest gateway status is 400.

Arangodb: 3.8.0
Jetty: 11.0.x

Arangodb installation: RPM
arango-secure-installation --configuration /etc/arangodb3/arango-secure-installation.conf 

java -jar admin-0.6.1.jar db-init arangodb://localhost/spline

export JETTY_HOME=/home/ec2-user/jetty-home-11.0.6
export JETTY_BASE=/home/ec2-user/jetty-restgw
cd $JETTY_BASE
export SPLINE_DATABASE_CONNECTION_URL=arangodb://localhost/spline
![Screen Shot 1400-05-21 at 19 33 27](https://user-images.githubusercontent.com/88126731/129190023-4236776b-2f29-4fa3-975b-0648f3ac943f.png)

java -jar $JETTY_HOME/start.jar

![Screen Shot 1400-05-21 at 19 27 46](https://user-images.githubusercontent.com/88126731/129189412-529e12b2-23c1-4d4f-809b-a7b840c2d676.png)

![Screen Shot 1400-05-21 at 19 27 29](https://user-images.githubusercontent.com/88126731/129189394-e912ac8c-e521-4483-8d56-64f051b35299.png)

## Question
![Screen Shot 1400-05-21 at 19 25 02](https://user-images.githubusercontent.com/88126731/129189141-6ccc412a-3de4-43a6-8d38-6b983eade883.png)

![Screen Shot 1400-05-21 at 19 25 29](https://user-images.githubusercontent.com/88126731/129189165-0141d3e0-448d-4a5a-a6e9-71062b532cb4.png)

I followed the official document to deploy spline.
How could I locate the root cause?

**Comment by cerveada** [comment]
Check Jetty logs, there may be more info.

**Comment by picomy** [comment]
2021-08-12 14:10:53.660:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
2021-08-12 14:10:53.684:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5456afaa{ROOT,/,file:///tmp/jetty-0_0_0_0-8080-ROOT_war-_-any-3242122244764707844/webapp/,AVAILABLE}{/home/ec2-user/jetty-restgw/webapps/ROOT.war}
2021-08-12 14:10:53.694:INFO :oejs.AbstractConnector:main: Started ServerConnector@1b28f282{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-08-12 14:10:53.706:INFO :oejs.Server:main: Started Server@1807e3f6{STARTING}[11.0.6,sto=5000] @2397ms

**Comment by picomy** [comment]
I replaced the Jetty 11.0.6 with Apache Tomcat 9.0.52. It worked well.

**Comment by picomy** [comment]
Jetty 9, 10, 11 didn't support spline 0.6.

**Comment by picomy** [comment]
It worked well with Tomcat

**Comment by wajda** [comment]
fixed for Jetty 9, in Spline v 0.7.2
