### ISSUE TITLE
WebUI wasn't able to work with kafka gateway

### ISSUE THREAD

**Issue by picomy** [AbsaOSS/spline#944]
## Background [Optional]

Startup Kafka gateway
port:7070

```shell
export CATALINA_HOME=/home/ec2-user/apache-tomcat-9.0.52
export CATALINA_BASE=/home/ec2-user/tomcat-spline-Kafkagw
export SPLINE_DATABASE_CONNECTION_URL=arangodb://localhost/spline
env spline.kafka.consumer.bootstrap.servers=localhost:9092 \
       spline.kafka.consumer.group.id=spline-group \
       spline.kafka.topic=spline-topic \
$CATALINA_HOME/bin/startup.sh
```

Startkup WebUI
port:9090

```shell
export CATALINA_HOME=/home/ec2-user/apache-tomcat-9.0.52
export CATALINA_BASE=/home/ec2-user/tomcat-spline-webui
export SPLINE_CONSUMER_URL=http://localhost:7070/consumer
$CATALINA_HOME/bin/startup.sh
```
## Question
The Web Server  displayed: Server is unavaliable.
![Screen Shot 1400-05-22 at 18 49 33](https://user-images.githubusercontent.com/88126731/129346990-363ee43d-8888-4954-aab8-b5be682b031d.png)

**Comment by cerveada** [comment]
Please check Kafka gateway logs. Are there any errors?

**Comment by wajda** [comment]
Kafka Gateway doesn't provide the Consumer API. You need to run REST Gateway as well.

We probably need to re-think how we split different APIs between apps.
