### ISSUE TITLE
Spline Server not working on Jetty

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#945]
According to #943 the server is not working on Jetty 11.

**Comment by wajda** [comment]
Fixed for Jetty 9.

However Jetty 10 and 11 uses different Servlet API versions and don't seem to be backward compatible. Spline currently uses Servlet API 3.1. Hence no support for Jetty 10+ at the moment.

> (from Jetty's documentation)
> Jetty Version | Servlet | License | Java
> -- | -- | -- | --
> Jetty 9.4.x | 3.1 | JavaEE 8/javax.servlet.* | Java 8
> Jetty 10.0.x | 4.0 | JakartaEE 8/javax.servlet.* | Java 11+
> Jetty 11.0.x | 5.0 | JakartaEE 9/jakartaee.servlet.* | Java 11+
>
