### ISSUE TITLE
Kafka default timeout set to 0 by default

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#956]
`spline.kafka.insertPlanTimeout`and `spline.kafka.insertEventTimeout` is 0 by default. 

This is caused by JNDIDataSource reading from `context.xml` where the value is missing.

### Workaround
set the properties manualy and overwrite the dafult.

**Comment by wajda** [comment]
Discussion notes:
- it happens because of `<Environment type="java.lang.Long">` defaults to `0` instead of `null`
- changing the type to `java.lang.String` fixes it, because string property defaults to `null` and type conversion happens implicitly.
